from pathlib import Path
import json,time,subprocess,hashlib,os
root=Path(__file__).resolve().parents[2];out=root/'docs/database/physical/wave4_m11_audit';report=root/'docs/reviews/P0.3.4_M1_1_temporal_remediation_audit.md'
while not report.exists():time.sleep(2)
q="SELECT UTC_TIMESTAMP(6),NAME,COUNT,STATUS FROM information_schema.innodb_metrics WHERE NAME IN ('lock_deadlocks','lock_timeouts','lock_row_lock_current_waits','lock_row_lock_waits','lock_row_lock_time');"
r=subprocess.run(['docker','exec','mepa-wave4-m11-independent-mysql','mysql','-uroot','--batch','-e',q],capture_output=True,text=True);(out/'innodb_metrics_final.txt').write_text(r.stdout+r.stderr,encoding='utf8')
s=report.read_text(encoding='utf8');s=s.replace('Os modos/índices/blockers capturados posteriormente constam de lock_wait_details.json; distinguir observação concreta de inferência sobre o mecanismo.', '**Modos de lock efectivamente capturados:** INSERT IGNORE independente pede `PRIMARY / X,INSERT_INTENTION / supremum pseudo-record`, bloqueado por `PRIMARY / X / supremum pseudo-record`; o blocked_claim pede `PRIMARY / X,REC_NOT_GAP / 1`, bloqueado na mesma row. Portanto a espera residual comprovada é no intervalo do índice clustered PRIMARY, não uma prova de contenção no prefixo da UNIQUE composta. A pré-criação não evita a tentativa de INSERT IGNORE com alocação AUTO_INCREMENT/checagem de duplicação. A origem exacta de aquisição do lock supremum requer trace interno adicional; não se inventa uma causalidade completa só a partir do nome do índice. Ver lock_wait_details.json/primary_supremum_wait_evidence.json.')
s=s.replace('O grafo é mapa de fontes, não prova de autorização.', 'O grafo é mapa de fontes, não prova de autorização. Nenhuma extracção/rebuild foi realizada; tokens de extracção novos: 0.')
s=s.replace('## Gate\n', 'Contadores InnoDB finais, globais de todo o servidor sintético desta passagem (não só do lote loaded):\n\n```text\n'+r.stdout.strip()+'\n```\n\n## Gate\n')
report.write_text(s,encoding='utf8')
# Query feedback affects graph memory only; preserve graph itself.
py=(root/'graphify-out/.graphify_python').read_text().strip();r=subprocess.run([py,'-m','graphify','save-result','--question','P0.3.4-M1.1-R Graphify inventory of temporal writers and boundaries','--answer','Expanded from graph vocabulary: evangelism service run; domain clock; campaign contact followup decision track step enroll integrate progress; child participation safety gate; discipleship enrollment scope. Thirteen deterministic queries returned WaveFour sources. Graph has 3439 nodes, 5714 edges and zero dangling edges. Security conclusions are separate SQL/runtime evidence; the graph is only a source map.','--type','query','--nodes','EvangelismService','DomainClock','DiscipleshipEnrollmentScope','ChildParticipationSafetyGate','--outcome','useful'],cwd=root,env={**os.environ,'PYTHONIOENCODING':'utf-8'},capture_output=True,text=True,encoding='utf8');(out/'graph_save_result.txt').write_text(r.stdout+r.stderr,encoding='utf8')
baseline=json.loads((out/'source_baseline.json').read_text());changed=[]
for name,h in baseline.items():
 if name=='docs/reviews/P0.3.4_wave4_gate.md':continue
 p=root/name
 if not p.exists() or hashlib.sha256(p.read_bytes()).hexdigest()!=h:changed.append(name)
gate=(root/'docs/reviews/P0.3.4_wave4_gate.md').read_bytes();oldhash=baseline['docs/reviews/P0.3.4_wave4_gate.md'];marker=gate.find(b'## Adenda P0.3.4-M1.1-R');prefix_preserved=any(hashlib.sha256(gate[:i]).hexdigest()==oldhash for i in range(max(0,marker-30),marker+1));graph=json.loads((out/'graph_queries.json').read_text());graph_same=hashlib.sha256((root/'graphify-out/graph.json').read_bytes()).hexdigest()==graph['graph_sha256']
check={'unexpected_source_changes':changed,'source_status':'PASS' if not changed else 'FAIL','gate_original_prefix_preserved':prefix_preserved,'graph_hash_preserved':graph_same,'report_last_line':report.read_text(encoding='utf8').strip().splitlines()[-1]};(out/'final_preservation.json').write_text(json.dumps(check,indent=2),encoding='utf8');print(json.dumps(check),flush=True)
# Stop only the new audit container; retain volume and schema data for review.
r=subprocess.run(['docker','stop','mepa-wave4-m11-independent-mysql'],capture_output=True,text=True);(out/'container_stop.txt').write_text(r.stdout+r.stderr,encoding='utf8');print('AUDIT_FINISHED',r.returncode,flush=True)
