<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `employments` -- Vínculo laboral MEPA (Pessoa + unidade empregadora); não é cargo eclesiástico nem situação profissional da Pessoa.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('employments')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table employments already exists; nothing changed.');
        }
        foreach (['people', 'organizational_units', 'legal_documents', 'users'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: employments requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `employments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `person_id` BIGINT UNSIGNED NOT NULL,
  `employing_unit_id` BIGINT UNSIGNED NOT NULL,
  `relationship_kind` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `job_title` VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NULL DEFAULT NULL,
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `end_reason` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `contract_document_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `open_guard` TINYINT UNSIGNED GENERATED ALWAYS AS (IF(`status` = 'ACTIVE', 1, NULL)) STORED,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `ended_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `ended_at` DATETIME(6) NULL DEFAULT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_employments_public_id` (`public_id`),
  UNIQUE KEY `uq_employments_person_id_unit_open` (`person_id`,`employing_unit_id`,`open_guard`),
  KEY `ix_employments_employing_unit_id_status` (`employing_unit_id`,`status`),
  KEY `ix_employments_contract_document_id` (`contract_document_id`),
  KEY `ix_employments_created_by` (`created_by`),
  KEY `ix_employments_ended_by` (`ended_by`),
  CONSTRAINT `fk_employments_person_id` FOREIGN KEY (`person_id`) REFERENCES `people` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employments_employing_unit_id` FOREIGN KEY (`employing_unit_id`) REFERENCES `organizational_units` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employments_contract_document_id` FOREIGN KEY (`contract_document_id`) REFERENCES `legal_documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employments_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employments_ended_by` FOREIGN KEY (`ended_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_employments_relationship_kind` CHECK (`relationship_kind` IN ('EMPLOYEE','BENEFICIARY')),
  CONSTRAINT `ck_employments_status` CHECK (`status` IN ('ACTIVE','ENDED')),
  CONSTRAINT `ck_employments_dates` CHECK (`ends_on` IS NULL OR `ends_on` >= `starts_on`),
  CONSTRAINT `ck_employments_ended` CHECK ((`status` = 'ENDED') = (`ends_on` IS NOT NULL AND `ended_at` IS NOT NULL AND `ended_by` IS NOT NULL AND `end_reason` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('employments')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: employments holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `employments`');
    }
};
