<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_run_lines` -- Linhas por vínculo e componente de um run (F2B); imutáveis a partir de APPROVED.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_run_lines')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_run_lines already exists; nothing changed.');
        }
        foreach (['payroll_runs', 'employments', 'compensation_component_types', 'payroll_rules'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_run_lines requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_run_lines` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `employment_id` BIGINT UNSIGNED NOT NULL,
  `component_type_id` BIGINT UNSIGNED NOT NULL,
  `base_amount` DECIMAL(19,4) NULL DEFAULT NULL,
  `rate` DECIMAL(9,6) NULL DEFAULT NULL,
  `amount` DECIMAL(19,4) NOT NULL,
  `source` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `rule_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_run_lines_run_employment_component` (`run_id`,`employment_id`,`component_type_id`),
  KEY `ix_payroll_run_lines_employment_id` (`employment_id`),
  KEY `ix_payroll_run_lines_component_type_id` (`component_type_id`),
  KEY `ix_payroll_run_lines_rule_id` (`rule_id`),
  CONSTRAINT `fk_payroll_run_lines_run_id` FOREIGN KEY (`run_id`) REFERENCES `payroll_runs` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_run_lines_employment_id` FOREIGN KEY (`employment_id`) REFERENCES `employments` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_run_lines_component_type_id` FOREIGN KEY (`component_type_id`) REFERENCES `compensation_component_types` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_run_lines_rule_id` FOREIGN KEY (`rule_id`) REFERENCES `payroll_rules` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_payroll_run_lines_source` CHECK (`source` IN ('FIXED','RULE','MANUAL')),
  CONSTRAINT `ck_payroll_run_lines_rule` CHECK ((`source` = 'RULE') = (`rule_id` IS NOT NULL)),
  CONSTRAINT `ck_payroll_run_lines_amount` CHECK (`amount` >= 0 AND `amount` = ROUND(`amount`, 2) AND (`base_amount` IS NULL OR `base_amount` >= 0))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_run_lines')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_run_lines holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_run_lines`');
    }
};
