<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_postings` -- Idempotência do posting do payroll no Finance (ACCRUAL, PAYMENT, REVERSAL); espelho de transfer_postings.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_postings')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_postings already exists; nothing changed.');
        }
        foreach (['payroll_runs', 'journal_entries'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_postings requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_postings` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `run_id` BIGINT UNSIGNED NOT NULL,
  `stage` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `entry_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_postings_run_id_stage` (`run_id`,`stage`),
  UNIQUE KEY `uq_payroll_postings_entry_id` (`entry_id`),
  CONSTRAINT `fk_payroll_postings_run_id` FOREIGN KEY (`run_id`) REFERENCES `payroll_runs` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_postings_entry_id` FOREIGN KEY (`entry_id`) REFERENCES `journal_entries` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_payroll_postings_stage` CHECK (`stage` IN ('ACCRUAL','PAYMENT','REVERSAL'))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_postings')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_postings holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_postings`');
    }
};
