<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_rule_brackets` -- Escalões de uma regra progressiva (BRACKET), sem lacunas nem sobreposição; valores só da fonte oficial.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_rule_brackets')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_rule_brackets already exists; nothing changed.');
        }
        foreach (['payroll_rules'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_rule_brackets requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_rule_brackets` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rule_id` BIGINT UNSIGNED NOT NULL,
  `lower_bound` DECIMAL(19,4) NOT NULL,
  `upper_bound` DECIMAL(19,4) NULL DEFAULT NULL,
  `rate` DECIMAL(9,6) NOT NULL,
  `fixed_amount` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `excess_over` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_rule_brackets_rule_id_lower_bound` (`rule_id`,`lower_bound`),
  CONSTRAINT `fk_payroll_rule_brackets_rule_id` FOREIGN KEY (`rule_id`) REFERENCES `payroll_rules` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_payroll_rule_brackets_bounds` CHECK (`lower_bound` >= 0 AND (`upper_bound` IS NULL OR `upper_bound` > `lower_bound`)),
  CONSTRAINT `ck_payroll_rule_brackets_rate` CHECK (`rate` >= 0 AND `rate` <= 1),
  CONSTRAINT `ck_payroll_rule_brackets_amounts` CHECK (`fixed_amount` >= 0 AND `excess_over` >= 0 AND `fixed_amount` = ROUND(`fixed_amount`, 2) AND `excess_over` = ROUND(`excess_over`, 2) AND `lower_bound` = ROUND(`lower_bound`, 2) AND (`upper_bound` IS NULL OR `upper_bound` = ROUND(`upper_bound`, 2)))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_rule_brackets')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_rule_brackets holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_rule_brackets`');
    }
};
