<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `employment_compensations` -- Histórico salarial append-only: componente por vínculo com vigência; alterar = fechar a vigente e abrir nova.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('employment_compensations')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table employment_compensations already exists; nothing changed.');
        }
        foreach (['employments', 'compensation_component_types', 'legal_documents', 'users'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: employment_compensations requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `employment_compensations` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `employment_id` BIGINT UNSIGNED NOT NULL,
  `component_type_id` BIGINT UNSIGNED NOT NULL,
  `amount` DECIMAL(19,4) NULL DEFAULT NULL,
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NULL DEFAULT NULL,
  `reason` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_document_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `open_guard` TINYINT UNSIGNED GENERATED ALWAYS AS (IF(`ends_on` IS NULL, 1, NULL)) STORED,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `closed_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `closed_at` DATETIME(6) NULL DEFAULT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_employment_compensations_start` (`employment_id`,`component_type_id`,`starts_on`),
  UNIQUE KEY `uq_employment_compensations_open` (`employment_id`,`component_type_id`,`open_guard`),
  KEY `ix_employment_compensations_component_type_id` (`component_type_id`),
  KEY `ix_employment_compensations_source_document_id` (`source_document_id`),
  KEY `ix_employment_compensations_created_by` (`created_by`),
  KEY `ix_employment_compensations_closed_by` (`closed_by`),
  CONSTRAINT `fk_employment_compensations_employment_id` FOREIGN KEY (`employment_id`) REFERENCES `employments` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employment_compensations_component_type_id` FOREIGN KEY (`component_type_id`) REFERENCES `compensation_component_types` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employment_compensations_source_document_id` FOREIGN KEY (`source_document_id`) REFERENCES `legal_documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employment_compensations_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_employment_compensations_closed_by` FOREIGN KEY (`closed_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_employment_compensations_dates` CHECK (`ends_on` IS NULL OR `ends_on` >= `starts_on`),
  CONSTRAINT `ck_employment_compensations_amount` CHECK (`amount` IS NULL OR (`amount` >= 0 AND `amount` = ROUND(`amount`, 2))),
  CONSTRAINT `ck_employment_compensations_closed` CHECK ((`closed_at` IS NULL) = (`closed_by` IS NULL) AND (`closed_at` IS NULL OR `ends_on` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('employment_compensations')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: employment_compensations holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `employment_compensations`');
    }
};
