<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `compensation_component_types` -- Catálogo de componentes remuneratórios (natureza, método, rubrica e passivo); sem valores nem taxas.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('compensation_component_types')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table compensation_component_types already exists; nothing changed.');
        }
        foreach (['financial_categories'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: compensation_component_types requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `compensation_component_types` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `name` VARCHAR(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `nature` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `calculation_method` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `expense_category_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `liability_role` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `is_active` TINYINT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME(6) NOT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_compensation_component_types_code` (`code`),
  KEY `ix_compensation_component_types_expense_category_id` (`expense_category_id`),
  CONSTRAINT `fk_compensation_component_types_expense_category_id` FOREIGN KEY (`expense_category_id`) REFERENCES `financial_categories` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_compensation_component_types_nature` CHECK (`nature` IN ('EARNING','EMPLOYEE_DEDUCTION','EMPLOYER_CHARGE')),
  CONSTRAINT `ck_compensation_component_types_calculation_method` CHECK (`calculation_method` IN ('FIXED_AMOUNT','RATE_RULE','BRACKET_RULE','MANUAL')),
  CONSTRAINT `ck_compensation_component_types_liability_role` CHECK (`liability_role` IS NULL OR `liability_role` IN ('PAYROLL_WITHHOLDINGS','PAYROLL_EMPLOYER_CHARGES')),
  CONSTRAINT `ck_compensation_component_types_posting` CHECK ((`nature` = 'EARNING' AND `expense_category_id` IS NOT NULL AND `liability_role` IS NULL) OR (`nature` = 'EMPLOYEE_DEDUCTION' AND `expense_category_id` IS NULL AND `liability_role` = 'PAYROLL_WITHHOLDINGS') OR (`nature` = 'EMPLOYER_CHARGE' AND `expense_category_id` IS NOT NULL AND `liability_role` = 'PAYROLL_EMPLOYER_CHARGES')),
  CONSTRAINT `ck_compensation_component_types_is_active` CHECK (`is_active` IN (0,1))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('compensation_component_types')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: compensation_component_types holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `compensation_component_types`');
    }
};
