<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_rules` -- Regras estatutárias versionadas (INSS, IRT, 13.º, férias, pensões…); nenhuma taxa é semeada; APPROVED exige fonte normativa.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_rules')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_rules already exists; nothing changed.');
        }
        foreach (['compensation_component_types', 'legal_documents', 'users'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_rules requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_rules` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `version` INT UNSIGNED NOT NULL,
  `component_type_id` BIGINT UNSIGNED NOT NULL,
  `method` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `rate` DECIMAL(9,6) NULL DEFAULT NULL,
  `starts_on` DATE NOT NULL,
  `ends_on` DATE NULL DEFAULT NULL,
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `source_document_id` BIGINT UNSIGNED NULL DEFAULT NULL,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `approved_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `approved_at` DATETIME(6) NULL DEFAULT NULL,
  `retired_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `retired_at` DATETIME(6) NULL DEFAULT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_rules_code_version` (`code`,`version`),
  KEY `ix_payroll_rules_component_type_id_status` (`component_type_id`,`status`),
  KEY `ix_payroll_rules_source_document_id` (`source_document_id`),
  KEY `ix_payroll_rules_created_by` (`created_by`),
  KEY `ix_payroll_rules_approved_by` (`approved_by`),
  KEY `ix_payroll_rules_retired_by` (`retired_by`),
  CONSTRAINT `fk_payroll_rules_component_type_id` FOREIGN KEY (`component_type_id`) REFERENCES `compensation_component_types` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_rules_source_document_id` FOREIGN KEY (`source_document_id`) REFERENCES `legal_documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_rules_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_rules_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_rules_retired_by` FOREIGN KEY (`retired_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_payroll_rules_method` CHECK (`method` IN ('FLAT_RATE','BRACKET')),
  CONSTRAINT `ck_payroll_rules_status` CHECK (`status` IN ('DRAFT','APPROVED','RETIRED')),
  CONSTRAINT `ck_payroll_rules_version` CHECK (`version` >= 1),
  CONSTRAINT `ck_payroll_rules_dates` CHECK (`ends_on` IS NULL OR `ends_on` >= `starts_on`),
  CONSTRAINT `ck_payroll_rules_rate` CHECK (`rate` IS NULL OR (`rate` >= 0 AND `rate` <= 1)),
  CONSTRAINT `ck_payroll_rules_method_rate` CHECK ((`method` = 'FLAT_RATE') = (`rate` IS NOT NULL)),
  CONSTRAINT `ck_payroll_rules_approved` CHECK ((`approved_at` IS NULL) = (`approved_by` IS NULL) AND (`status` = 'DRAFT' OR `approved_at` IS NOT NULL OR `status` = 'RETIRED') AND (`approved_at` IS NULL OR `source_document_id` IS NOT NULL)),
  CONSTRAINT `ck_payroll_rules_segregation` CHECK (`approved_by` IS NULL OR `approved_by` <> `created_by`),
  CONSTRAINT `ck_payroll_rules_retired` CHECK ((`status` = 'RETIRED') = (`retired_at` IS NOT NULL) AND (`retired_at` IS NULL) = (`retired_by` IS NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_rules')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_rules holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_rules`');
    }
};
