<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_runs` -- Processamento salarial por unidade empregadora e mês de serviço (F2B); totais agregados e input_hash.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_runs')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_runs already exists; nothing changed.');
        }
        foreach (['organizational_units', 'accounting_periods', 'users'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_runs requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `public_id` CHAR(26) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `employing_unit_id` BIGINT UNSIGNED NOT NULL,
  `period_id` BIGINT UNSIGNED NOT NULL,
  `run_kind` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sequence` INT UNSIGNED NOT NULL,
  `status` VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `input_hash` BINARY(32) NULL DEFAULT NULL,
  `gross_amount` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `deductions_amount` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `employer_charges_amount` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `net_amount` DECIMAL(19,4) NOT NULL DEFAULT 0.0000,
  `headcount` INT UNSIGNED NOT NULL DEFAULT 0,
  `regular_guard` TINYINT UNSIGNED GENERATED ALWAYS AS (IF(`run_kind` = 'REGULAR' AND `status` <> 'CANCELLED', 1, NULL)) STORED,
  `created_by` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `calculated_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `calculated_at` DATETIME(6) NULL DEFAULT NULL,
  `approved_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `approved_at` DATETIME(6) NULL DEFAULT NULL,
  `posted_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `posted_at` DATETIME(6) NULL DEFAULT NULL,
  `paid_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `paid_at` DATETIME(6) NULL DEFAULT NULL,
  `cancelled_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `cancelled_at` DATETIME(6) NULL DEFAULT NULL,
  `cancel_reason` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `reversed_by` BIGINT UNSIGNED NULL DEFAULT NULL,
  `reversed_at` DATETIME(6) NULL DEFAULT NULL,
  `reversal_reason` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL,
  `lock_version` INT UNSIGNED NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_runs_unit_period_kind_sequence` (`employing_unit_id`,`period_id`,`run_kind`,`sequence`),
  UNIQUE KEY `uq_payroll_runs_public_id` (`public_id`),
  UNIQUE KEY `uq_payroll_runs_unit_period_regular` (`employing_unit_id`,`period_id`,`regular_guard`),
  KEY `ix_payroll_runs_period_id` (`period_id`),
  KEY `ix_payroll_runs_created_by` (`created_by`),
  KEY `ix_payroll_runs_calculated_by` (`calculated_by`),
  KEY `ix_payroll_runs_approved_by` (`approved_by`),
  KEY `ix_payroll_runs_posted_by` (`posted_by`),
  KEY `ix_payroll_runs_paid_by` (`paid_by`),
  KEY `ix_payroll_runs_cancelled_by` (`cancelled_by`),
  KEY `ix_payroll_runs_reversed_by` (`reversed_by`),
  CONSTRAINT `fk_payroll_runs_employing_unit_id` FOREIGN KEY (`employing_unit_id`) REFERENCES `organizational_units` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_period_id` FOREIGN KEY (`period_id`) REFERENCES `accounting_periods` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_calculated_by` FOREIGN KEY (`calculated_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_approved_by` FOREIGN KEY (`approved_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_posted_by` FOREIGN KEY (`posted_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_paid_by` FOREIGN KEY (`paid_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_cancelled_by` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_runs_reversed_by` FOREIGN KEY (`reversed_by`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_payroll_runs_run_kind` CHECK (`run_kind` IN ('REGULAR','HOLIDAY_SUBSIDY','THIRTEENTH','ADJUSTMENT')),
  CONSTRAINT `ck_payroll_runs_status` CHECK (`status` IN ('DRAFT','CALCULATED','APPROVED','POSTED','PAID','CANCELLED','REVERSED')),
  CONSTRAINT `ck_payroll_runs_sequence` CHECK (`sequence` >= 1),
  CONSTRAINT `ck_payroll_runs_amounts` CHECK (`gross_amount` >= 0 AND `deductions_amount` >= 0 AND `employer_charges_amount` >= 0 AND `net_amount` >= 0 AND `net_amount` = `gross_amount` - `deductions_amount`),
  CONSTRAINT `ck_payroll_runs_calculated` CHECK (`status` IN ('DRAFT','CANCELLED') OR (`calculated_at` IS NOT NULL AND `calculated_by` IS NOT NULL AND `input_hash` IS NOT NULL)),
  CONSTRAINT `ck_payroll_runs_approved` CHECK (`status` NOT IN ('APPROVED','POSTED','PAID','REVERSED') OR (`approved_at` IS NOT NULL AND `approved_by` IS NOT NULL)),
  CONSTRAINT `ck_payroll_runs_segregation` CHECK (`approved_by` IS NULL OR `calculated_by` IS NULL OR `approved_by` <> `calculated_by`),
  CONSTRAINT `ck_payroll_runs_posted` CHECK (`status` NOT IN ('POSTED','PAID','REVERSED') OR (`posted_at` IS NOT NULL AND `posted_by` IS NOT NULL)),
  CONSTRAINT `ck_payroll_runs_paid` CHECK ((`status` = 'PAID') = (`paid_at` IS NOT NULL AND `paid_by` IS NOT NULL)),
  CONSTRAINT `ck_payroll_runs_cancelled` CHECK ((`status` = 'CANCELLED') = (`cancelled_at` IS NOT NULL AND `cancelled_by` IS NOT NULL AND `cancel_reason` IS NOT NULL)),
  CONSTRAINT `ck_payroll_runs_reversed` CHECK ((`status` = 'REVERSED') = (`reversed_at` IS NOT NULL AND `reversed_by` IS NOT NULL AND `reversal_reason` IS NOT NULL))
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_runs')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_runs holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_runs`');
    }
};
