<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

// P0.10-F2A Payroll (ADR 0021 D23-D27, D32/D33 + D-04A.14/15): `payroll_rule_base_components` -- Componentes que formam a base de incidência de uma versão de regra.
// Generated by scripts/generate-p010-payroll-schema.py (one specification for migration, catalog, dictionary, ERD, manifest).
// Preconditions are explicit: qualified MySQL driver, the table must not exist, every referenced table must exist.
// down() refuses to drop a table that holds rows (no silent data loss); it drops only this table.
return new class extends Migration
{
    public function up(): void
    {
        if (DB::getDriverName() !== 'mysql') {
            throw new RuntimeException('P0.10 requires the qualified MySQL driver; SQLite is not supported.');
        }
        if (Schema::hasTable('payroll_rule_base_components')) {
            throw new RuntimeException('P010_PRECONDITION_FAILED: table payroll_rule_base_components already exists; nothing changed.');
        }
        foreach (['payroll_rules', 'compensation_component_types'] as $required) {
            if (!Schema::hasTable($required)) {
                throw new RuntimeException('P010_PRECONDITION_FAILED: payroll_rule_base_components requires table ' . $required . '; nothing changed.');
            }
        }

        DB::statement(<<<'SQL'
CREATE TABLE `payroll_rule_base_components` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `rule_id` BIGINT UNSIGNED NOT NULL,
  `component_type_id` BIGINT UNSIGNED NOT NULL,
  `created_at` DATETIME(6) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_payroll_rule_base_components_rule_component` (`rule_id`,`component_type_id`),
  KEY `ix_payroll_rule_base_components_component_type_id` (`component_type_id`),
  CONSTRAINT `fk_payroll_rule_base_components_rule_id` FOREIGN KEY (`rule_id`) REFERENCES `payroll_rules` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_payroll_rule_base_components_component_type_id` FOREIGN KEY (`component_type_id`) REFERENCES `compensation_component_types` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
SQL
        );
    }

    public function down(): void
    {
        if (DB::table('payroll_rule_base_components')->exists()) {
            throw new RuntimeException('P010_ROLLBACK_REFUSED: payroll_rule_base_components holds rows; rollback never deletes payroll data.');
        }
        DB::statement('DROP TABLE `payroll_rule_base_components`');
    }
};
