// P0.10-F2A RH / payroll foundation (ADR 0021 D23-D28 + D-04A.15). Public ids only; money is a decimal string.
export interface HrRef { public_id: string; name: string }
export interface HrUnit extends HrRef { type: string; permissions: string[] }
export interface HrComponent { code: string; label: string; nature: 'EARNING' | 'EMPLOYEE_DEDUCTION' | 'EMPLOYER_CHARGE'; calculation_method: 'FIXED_AMOUNT' | 'RATE_RULE' | 'BRACKET_RULE' | 'MANUAL'; rule_based: boolean; rubric: string | null; liability_role: string | null; active: boolean }
export interface HrProduction { enabled: boolean; status: 'ENABLED' | 'DISABLED'; code: string | null; operations: Record<'calculate' | 'approve' | 'post' | 'pay', boolean>; engine: string }
export interface HrContext { permissions: string[]; units: HrUnit[]; components: HrComponent[]; production: HrProduction; relationship_kinds: string[] }
export interface EmploymentSummary { public_id: string; person: HrRef; unit: HrRef; relationship_kind: string; job_title: string | null; starts_on: string; ends_on: string | null; status: 'ACTIVE' | 'ENDED' }
export interface CompensationLine { component: { code: string; label: string; nature: string; calculation_method: string }; amount: string | null; currency: 'AOA'; rule_based: boolean; starts_on: string; ends_on: string | null; reason: string; source_document: { public_id: string } | null; effective: boolean; closed: boolean; recorded_at: string }
export interface Compensation { as_of: string; current: CompensationLine[]; history: CompensationLine[] }
export interface EmploymentHistoryItem { public_id: string; unit: HrRef; relationship_kind: string; job_title: string | null; starts_on: string; ends_on: string | null; status: string; end_reason: string | null; current: boolean }
export interface EmploymentDetail extends Omit<EmploymentSummary, 'person'> { person: HrRef; end_reason: string | null; contract_document: { public_id: string | null } | null; created_at: string; history: EmploymentHistoryItem[]; actions: string[]; compensation_visible: boolean; compensation?: Compensation }
export interface CompensationOverview { unit: HrRef; as_of: string; data: { employment: string; person: HrRef; job_title: string | null; base_salary: string | null; fixed_earnings: string; components: number }[] }
export interface PayrollRuleSummary { code: string; version: number; component: string; method: 'FLAT_RATE' | 'BRACKET'; rate: string | null; starts_on: string; ends_on: string | null; status: 'DRAFT' | 'APPROVED' | 'RETIRED'; source_document: { public_id: string | null } | null; provenance: { created_by: string | null; created_at: string; approved_by: string | null; approved_at: string | null; retired_at: string | null; drafted_by_me: boolean }; actions: string[] }
export interface PayrollRuleDetail extends PayrollRuleSummary { base_components: string[]; brackets: { lower_bound: string; upper_bound: string | null; rate: string; fixed_amount: string; excess_over: string }[] }
export interface PayrollRules { data: PayrollRuleSummary[]; coverage_today: { date: string; components: { component: string; label: string; status: string; rule: { code: string; version: number } | null }[] } }
export interface ReadinessIssue { code: string; employment?: string; component?: string; reason?: string }
export interface PayrollReadiness { unit: HrRef; period: { code: string; from: string; to: string }; configuration: { status: 'READY' | 'NOT_READY'; issues: ReadinessIssue[]; employments: number; rules: { component: string; rule: { code: string; version: number } }[] }; production: HrProduction & { issues: { code: string }[] }; input_hash_preview: { algorithm: string; version: string; run_kind: string; sequence: number; value: string } | null }
