'use strict';
const fs=require('node:fs');
const out='docs/database/physical/';
const read=name=>JSON.parse(fs.readFileSync(out+name,'utf8'));
const summary=read('wave4_test_summary.json');
const graph=read('wave4_graphify_validation.json');
const contracts=read('wave4_approved_contracts_validation.json');
const rules=read('wave4_application_rules_tracking.json');
if(!['TESTS_PASS','WAVE4_READY_FOR_AUDIT'].includes(summary.status)||summary.totals.failures||summary.totals.errors||summary.wave4_totals.skipped)throw Error('Final tests required');
if(summary.physical_validation.status!=='STRICT_PARITY_PASS'||summary.static_validation.status!=='STRICT_PARITY_PASS'||contracts.drift||summary.documents.errors.length)throw Error('Strict parity/contracts required');
if(!graph.queries_pass||graph.shrink_guard!=='PASS'||!graph.shrink_rejection_probe||graph.force_used)throw Error('Graphify guard/query coverage required');
if(rules.rules.some(r=>r.implementation_wave===4&&r.status!=='IMPLEMENTED_TESTED'))throw Error('Wave 4 rule tracking incomplete');
summary.graphify=graph;
summary.status='WAVE4_READY_FOR_AUDIT';
summary.ready_for_audit=true;
summary.open_institutional_decisions='D-02 through D-12 unchanged; activation remains blocked where applicable';
fs.writeFileSync(out+'wave4_test_summary.json',JSON.stringify(summary,null,2)+'\n');
let report=fs.readFileSync('docs/reviews/P0.3.4_wave4_implementation.md','utf8');
report=report.replace('Estado: testes Wave 4 concluídos; regressão final Wave 3 e Graphify em verificação.','Estado: pronta para auditoria; todas as provas finais e Graphify passaram.');
report=report.replace(/\| Graphify \| [^\n]+/,`| Graphify | PASS — ${graph.before_nodes} → ${graph.after_nodes} nodes; ${graph.queries} consultas; shrink guard e rejeição de scratch verificados, sem force |`);
report=report.replace('P0.3.4 — WAVE 4 COM PENDÊNCIAS','P0.3.4 — WAVE 4 PRONTA PARA AUDITORIA');
fs.writeFileSync('docs/reviews/P0.3.4_wave4_implementation.md',report);
fs.writeFileSync(out+'P0.3.4_wave4_report.md',report);
const final={phase:'P0.3.4',status:'INTERNAL_GATE_PASS_READY_FOR_INDEPENDENT_AUDIT',tests:summary.totals,wave4:summary.wave4_totals,fresh:'PASS',upgrade:'PASS',rollback:'EMPTY_PASS_DURABLE_DATA_REFUSED_WITHOUT_LOSS',remigrate:'PASS',strict_parity:'PASS',unexpected_drift:0,approved_contracts_drift:0,documents_errors:0,graphify:'PASS',wave5_started:false,institutional_decisions_modified:false};
fs.writeFileSync(out+'wave4_final_validation.json',JSON.stringify(final,null,2)+'\n');
console.log(JSON.stringify(final,null,2));