"""P0.5-I People / Families end-to-end runner (Test Infrastructure V2).

Sequence (every step recorded in docs/reviews/evidence/P0.5-I/e2e-run.json):
  1. tools/test-infrastructure/mysql_instance.py init-start --port auto  -> STARTED_VERIFIED
  2. tools/test-infrastructure/pool.py create-and-migrate                  -> Wave 3/4/5 pools (+ P0.5 delta)
  3. schema parity of the pool against the Wave 1 catalog + ADR-0017 delta (+ in-memory drift probes)
  4. PHPUnit suites passed on the command line (optional, --phpunit) and M1..M10 mutation probes (--mutations)
  5. PeopleE2EFixtureTest seeds the synthetic browser fixture
  6. production build of apps/web with VITE_API_URL -> 127.0.0.1:18080
  7. Laravel served by PHP's built-in server with a PROCESS-ONLY environment (APP_ENV=e2e, pool DSN,
     synthetic auth statuses, a key ring generated in the OS temp directory); vite preview on 14173
  8. Playwright People suite (playwright.people.config.ts)
  9. Academy regression: AcademyE2EFixtureTest + tests/e2e/academy.spec.ts (default config)
  10. servers stopped, log scanned for key material / E2E plaintext, key ring deleted,
     mysql_instance.py stop -> STOPPED_VERIFIED
No development (3306/laravel) database is touched and no secret is written inside the repository.
Tracked Academy evidence regenerated by step 8 must be restored afterwards (git checkout).
"""
import argparse
import base64
import json
import os
import secrets
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
API = REPO / "apps" / "api"
WEB = REPO / "apps" / "web"
PHP = os.environ.get("MEPA_PHP_BIN", r"C:\wamp64\bin\php\php8.1.33\php.exe")
EVIDENCE = REPO / "docs" / "reviews" / "evidence" / "P0.5-I"
# Fixed by apps/web/playwright.people.config.ts (the People reporter always writes here).
PEOPLE_PLAYWRIGHT = REPO / "docs" / "reviews" / "evidence" / "P0.5-I" / "playwright-results.json"
NPX = "npx.cmd" if os.name == "nt" else "npx"
NPM = "npm.cmd" if os.name == "nt" else "npm"


def run(cmd, cwd, env=None, timeout=1800):
    started = time.time()
    proc = subprocess.run(cmd, cwd=cwd, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=timeout)
    return {"cmd": " ".join(str(c) for c in cmd if "keyring" not in str(c)), "rc": proc.returncode, "seconds": round(time.time() - started, 1), "stdout_tail": proc.stdout[-4000:], "stderr_tail": proc.stderr[-2000:]}


def last_json(text):
    start = text.rfind("\n{")
    start = 0 if start < 0 else start
    return json.loads(text[text.find("{", start):])


def wait_http(url, seconds=60):
    deadline = time.time() + seconds
    while time.time() < deadline:
        try:
            with urllib.request.urlopen(url, timeout=3) as response:
                if response.status < 500:
                    return True
        except Exception:
            time.sleep(0.5)
    return False


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--phpunit", nargs="*", default=[], help="DatabaseV2/Unit/Feature test files to run on the pools")
    parser.add_argument("--skip-academy", action="store_true")
    parser.add_argument("--mutations", action="store_true", help="run scripts/p05-people-mutation-probes.py (M1-M13) on the pool")
    parser.add_argument("--evidence", default=None, help="repo-relative evidence directory (default docs/reviews/evidence/P0.5-I)")
    args = parser.parse_args()
    global EVIDENCE
    if args.evidence:
        EVIDENCE = REPO / args.evidence

    EVIDENCE.mkdir(parents=True, exist_ok=True)
    report = {"runner": "scripts/run-p05-people-e2e.py", "steps": []}
    keyring_dir = Path(tempfile.mkdtemp(prefix="mepa-people-e2e-"))
    keyring = keyring_dir / "keyring.json"
    enc, mac = secrets.token_bytes(32), secrets.token_bytes(32)
    keyring.write_text(json.dumps({"active_version": 1, "keys": {"1": {"encryption": base64.b64encode(enc).decode(), "blind_index": base64.b64encode(mac).decode()}}}), encoding="utf-8")
    report["keyring"] = {"location": "OS temp directory, outside the repository", "inside_repository": str(keyring).lower().startswith(str(REPO).lower()), "distinct_keys": enc != mac}
    servers = []
    port = None
    log_path = API / "storage" / "logs" / "laravel.log"
    log_offset = log_path.stat().st_size if log_path.exists() else 0
    try:
        start = run([sys.executable, "tools/test-infrastructure/mysql_instance.py", "init-start", "--port", "auto"], REPO, timeout=600)
        report["steps"].append({"step": "mysql_instance.init-start", **start})
        info = last_json(start["stdout_tail"])
        report["infrastructure_start"] = info.get("status")
        if info.get("status") != "STARTED_VERIFIED":
            raise RuntimeError("instance not verified")
        port, session = int(info["port"]), info["session_id"]
        pool = run([sys.executable, "tools/test-infrastructure/pool.py", "create-and-migrate", "--port", str(port)], REPO, timeout=1200)
        report["steps"].append({"step": "pool.create-and-migrate", **pool})
        report["pools"] = last_json(pool["stdout_tail"])["migrated"]
        short = session[:8]
        wave5 = f"mepa_wave5_test_{short}_pool_01"
        test_env = {**os.environ, "XDEBUG_MODE": "off",
                    "WAVE5_DSN": f"mysql:host=127.0.0.1;port={port};dbname={wave5}", "WAVE5_USER": "root", "WAVE5_PASSWORD": "", "WAVE5_ALLOW_SYNTHETIC": "1",
                    "WAVE4_DSN": f"mysql:host=127.0.0.1;port={port};dbname=mepa_wave4_test_{short}_pool_01", "WAVE4_USER": "root", "WAVE4_PASSWORD": "", "WAVE4_ALLOW_SYNTHETIC": "1",
                    "WAVE3_DSN": f"mysql:host=127.0.0.1;port={port};dbname=mepa_wave3_test_{short}_pool_01", "WAVE3_USER": "root", "WAVE3_PASSWORD": "", "WAVE3_ALLOW_SYNTHETIC": "1"}
        parity_env = {**os.environ, "PHP_BIN": PHP, "P05_DSN": f"mysql:host=127.0.0.1;port={port};dbname={wave5}", "P05_USER": "root", "P05_PASSWORD": ""}
        parity = run(["node", "scripts/validate-p05-people-schema.cjs", "--output", str(EVIDENCE / "schema-parity.json")], REPO, parity_env)
        report["schema_parity"] = {"rc": parity["rc"], "status": json.loads((EVIDENCE / "schema-parity.json").read_text(encoding="utf-8"))["status"]}
        drift = run(["node", "scripts/validate-p05-people-schema.cjs", "--probe"], REPO, parity_env)
        (EVIDENCE / "schema-parity-probes.json").write_text(drift["stdout_tail"], encoding="utf-8", newline="\n")
        report["schema_parity_probes"] = {"rc": drift["rc"], "status": json.loads(drift["stdout_tail"])["status"]}
        report["phpunit"] = []
        for test in args.phpunit:
            result = run([PHP, "vendor/phpunit/phpunit/phpunit", test], API, test_env, timeout=1800)
            summary = [line for line in result["stdout_tail"].splitlines() if line.startswith(("OK (", "Tests:", "FAILURES", "ERRORS"))]
            report["phpunit"].append({"file": test, "rc": result["rc"], "summary": summary, "seconds": result["seconds"]})
        if args.mutations:
            mutations = run([sys.executable, "scripts/p05-people-mutation-probes.py", "--out", str((EVIDENCE / "mutation-probes.json").relative_to(REPO))], REPO, test_env, timeout=3600)
            report["mutation_probes"] = {"rc": mutations["rc"], "summary": mutations["stdout_tail"].strip().splitlines()}
        fixture = run([PHP, "vendor/phpunit/phpunit/phpunit", "tests/DatabaseV2/PeopleE2EFixtureTest.php"], API, test_env)
        report["steps"].append({"step": "people_fixture", **fixture})
        if fixture["rc"] != 0:
            raise RuntimeError("people fixture failed")

        build = run([NPM, "run", "build"], WEB, {**os.environ, "VITE_API_URL": "http://127.0.0.1:18080/api/v1"}, timeout=900)
        report["steps"].append({"step": "web_build", **build})
        if build["rc"] != 0:
            raise RuntimeError("build failed")

        server_env = {**os.environ, "APP_ENV": "e2e", "APP_DEBUG": "false", "DB_CONNECTION": "mysql", "DB_HOST": "127.0.0.1", "DB_PORT": str(port),
                      "DB_DATABASE": wave5, "DB_USERNAME": "root", "DB_PASSWORD": "", "AUTH_ACTIVE_USER_STATUSES": "SYNTHETIC_READY",
                      "AUTH_ACTIVE_GRANT_STATUSES": "SYNTHETIC_READY", "ACADEMY_E2E_TEST_POLICY": "true", "PEOPLE_KEYRING_PATH": str(keyring),
                      "CACHE_DRIVER": "file", "MEPA_PHP_BIN": PHP}
        router = API / "vendor" / "laravel" / "framework" / "src" / "Illuminate" / "Foundation" / "resources" / "server.php"
        servers.append(subprocess.Popen([PHP, "-S", "127.0.0.1:18080", str(router)], cwd=API / "public", env=server_env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL))
        servers.append(subprocess.Popen([NPX, "vite", "preview", "--host", "127.0.0.1", "--port", "14173", "--strictPort"], cwd=WEB, env=os.environ.copy(), stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL))
        report["servers_ready"] = {"api": wait_http("http://127.0.0.1:18080/api/v1/health"), "web": wait_http("http://127.0.0.1:14173/entrar")}

        people = run([NPX, "playwright", "test", "--config", "playwright.people.config.ts"], WEB, server_env, timeout=1800)
        report["steps"].append({"step": "playwright_people", **people})
        if PEOPLE_PLAYWRIGHT.parent != EVIDENCE:
            shutil.copyfile(PEOPLE_PLAYWRIGHT, EVIDENCE / "playwright-results.json")
        results = json.loads((EVIDENCE / "playwright-results.json").read_text(encoding="utf-8"))
        report["playwright_people"] = results.get("stats", {})

        if not args.skip_academy:
            academy_fixture = run([PHP, "vendor/phpunit/phpunit/phpunit", "tests/DatabaseV2/AcademyE2EFixtureTest.php"], API, test_env)
            report["steps"].append({"step": "academy_fixture", **academy_fixture})
            academy = run([NPX, "playwright", "test", "tests/e2e/academy.spec.ts"], WEB, server_env, timeout=1800)
            report["steps"].append({"step": "playwright_academy_regression", **academy})
            academy_results = REPO / "docs" / "reviews" / "evidence" / "P0.3.5-A4.2" / "playwright-results.json"
            report["playwright_academy"] = json.loads(academy_results.read_text(encoding="utf-8")).get("stats", {})
    finally:
        for proc in servers:
            if os.name == "nt":
                subprocess.run(["taskkill", "/PID", str(proc.pid), "/T", "/F"], capture_output=True)
            else:
                proc.terminate()
        leaked = []
        if log_path.exists():
            with open(log_path, "rb") as handle:
                handle.seek(log_offset)
                tail = handle.read()
            for label, needle in [("encryption_key_b64", base64.b64encode(enc)), ("blind_index_key_b64", base64.b64encode(mac)), ("encryption_key_raw", enc), ("blind_index_key_raw", mac),
                                  ("e2e_phone", b"923 000 111"), ("e2e_address", "Rua E2E da Missão".encode())]:
                if needle in tail:
                    leaked.append(label)
            report["log_scan"] = {"bytes_scanned": len(tail), "leaks": leaked}
        shutil.rmtree(keyring_dir, ignore_errors=True)
        report["keyring"]["deleted_after_run"] = not keyring.exists()
        if port is not None:
            stop = run([sys.executable, "tools/test-infrastructure/mysql_instance.py", "stop", "--port", str(port)], REPO, timeout=600)
            report["steps"].append({"step": "mysql_instance.stop", **stop})
            try:
                report["infrastructure_stop"] = last_json(stop["stdout_tail"]).get("status")
            except Exception:
                report["infrastructure_stop"] = "UNPARSED"
        for step in report["steps"]:
            step["stdout_tail"] = step["stdout_tail"][-1500:]
        (EVIDENCE / "e2e-run.json").write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(json.dumps({k: report.get(k) for k in ("infrastructure_start", "schema_parity", "schema_parity_probes", "phpunit", "mutation_probes", "servers_ready", "playwright_people", "playwright_academy", "log_scan", "infrastructure_stop")}, indent=2))


if __name__ == "__main__":
    main()
