import { useEffect, useState, type FormEvent } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { ActionForm, DataTable, Dialog, EmptyState, ErrorState, Field, LoadingState, PageHeader, Pagination, StatusBadge, type Column } from '../components/ui'
import { useApp } from '../context/AppContext'
import { useAcademyItem, useAcademyPage, useListQuery } from '../hooks/useAcademy'
import { academyPatch, academyPost, academyPut } from '../lib/academy/client'
import { ep } from '../lib/academy/endpoints'
import { toUiError, type UiError } from '../lib/academy/errors'
import { optionsFor, targetsFor, VOCABULARY_PENDING_MESSAGE } from '../lib/academy/vocabulary'
import { formatDateTime, formatNumber } from '../lib/format'
import type { Assessment, AssessmentAttempt, Certificate, ClassDetail, EligibleFile, GradeVersion, Item, ProgressPayload, RosterRow, Transcript, TranscriptSummary } from '../types/academy'

export function AttendancePage() {
  type Row = { enrollment_public_id: string; display_name: string; status?: string; recorded_at?: string; lock_version?: number }
  const { sessionId } = useParams(); const { capabilities, vocabulary, notify } = useApp(); const { query, update } = useListQuery(false); const result = useAcademyPage<Row>(sessionId ? ep.sessionAttendance(sessionId) : null, query); const statuses = optionsFor(vocabulary, 'attendance.statuses'); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  useEffect(() => { if (result.data) setDrafts(Object.fromEntries(result.data.data.map((row) => [row.enrollment_public_id, row.status ?? '']))) }, [result.data])
  async function saveOne(row: Row) { if (!sessionId || !drafts[row.enrollment_public_id]) return; setBusy(true); setError(null); try { await academyPut(ep.sessionAttendanceRecord(sessionId, row.enrollment_public_id), { attendance_status: drafts[row.enrollment_public_id], lock_version: row.lock_version }); notify('Presença guardada.'); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  async function saveBulk() { if (!sessionId || !result.data) return; const entries = result.data.data.filter((row) => drafts[row.enrollment_public_id]).map((row) => ({ enrollment: row.enrollment_public_id, attendance_status: drafts[row.enrollment_public_id] })); if (entries.length === 0 || entries.length > 200 || !window.confirm(`Guardar ${entries.length} registos de presença numa operação?`)) return; setBusy(true); setError(null); try { await academyPost(ep.sessionAttendanceBulk(sessionId), { entries }); notify('Folha de presenças guardada.'); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  const canWrite = capabilities.can('canRecordAttendance') && Boolean(statuses)
  return <><PageHeader title="Presenças" description="Roster da sessão, paginado no servidor." back={{ to: '/academia/turmas', label: 'Voltar às turmas' }} actions={canWrite ? <button className="btn btn--primary" disabled={busy} onClick={saveBulk}>Guardar folha</button> : undefined} />{error && <ErrorState error={error} />}{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState title="Roster vazio" />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.enrollment_public_id} columns={[{ key: 'name', label: 'Pessoa', render: (r) => r.display_name }, { key: 'status', label: 'Presença', render: (r) => canWrite ? <select className="select" aria-label={`Presença de ${r.display_name}`} value={drafts[r.enrollment_public_id] ?? ''} onChange={(e) => setDrafts((current) => ({ ...current, [r.enrollment_public_id]: e.target.value }))}><option value="">Seleccionar</option>{statuses?.map((status) => <option key={status.value} value={status.value}>{status.label}</option>)}</select> : <StatusBadge value={r.status} /> }, { key: 'date', label: 'Registo', render: (r) => formatDateTime(r.recorded_at) }, { key: 'action', label: '', render: (r) => canWrite ? <button className="btn btn--secondary btn--sm" disabled={busy || !drafts[r.enrollment_public_id]} onClick={() => saveOne(r)}>Guardar</button> : null }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}{!statuses && <div className="alert alert--warning"><span className="alert__icon">i</span><div className="alert__body"><strong>Registo de presença indisponível</strong><p>{VOCABULARY_PENDING_MESSAGE}</p></div></div>}</>
}

export function AssessmentsPage() {
  const { classId } = useParams(); const { capabilities, notify } = useApp(); const { query, update, searchInput, changeSearch } = useListQuery(true); const classItem = useAcademyItem<ClassDetail>(classId ? ep.classDetail(classId) : null); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [maxScore, setMaxScore] = useState(''); const [passScore, setPassScore] = useState(''); const [attempts, setAttempts] = useState('1'); const [weight, setWeight] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  const result = useAcademyPage<Assessment>(classId ? ep.classAssessments(classId) : null, query)
  const columns: Column<Assessment>[] = [{ key: 'name', label: 'Avaliação', render: (r) => r.name }, { key: 'max', label: 'Máximo', render: (r) => formatNumber(r.max_score) }, { key: 'weight', label: 'Peso', render: (r) => formatNumber(r.weight) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/avaliacoes/${r.public_id}`}>Abrir</Link> }]
  async function create(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!classItem.data) return; setBusy(true); setError(null); try { await academyPost(ep.assessmentCreate(classItem.data.course_version_id), { name, max_score: Number(maxScore), pass_score: passScore === '' ? null : Number(passScore), max_attempts: Number(attempts), weight: Number(weight) }); notify('Avaliação criada.'); setOpen(false); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title="Avaliações" description="Avaliações associadas à versão do curso." back={{ to: `/academia/turmas/${classId}`, label: 'Voltar à turma' }} actions={capabilities.can('canManage') ? <button className="btn btn--primary" onClick={() => setOpen(true)}>Criar avaliação</button> : undefined} /><div className="card"><label className="field"><span className="field__label">Pesquisar</span><input className="input" value={searchInput} onChange={(e) => changeSearch?.(e.target.value)} /></label></div>{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} columns={columns} rowKey={(r) => r.public_id} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}<Dialog open={open} title="Criar avaliação" onClose={() => setOpen(false)}><ActionForm busy={busy} submitLabel="Criar" onSubmit={create} error={error}><Field label="Nome" name="assessment-name" required><input id="assessment-name" className="input" value={name} onChange={(e) => setName(e.target.value)} required /></Field><Field label="Nota máxima" name="assessment-max" required><input id="assessment-max" className="input" type="number" min="0" step="any" value={maxScore} onChange={(e) => setMaxScore(e.target.value)} required /></Field><Field label="Nota de referência" name="assessment-pass"><input id="assessment-pass" className="input" type="number" min="0" step="any" value={passScore} onChange={(e) => setPassScore(e.target.value)} /></Field><Field label="Tentativas" name="assessment-attempts" required><input id="assessment-attempts" className="input" type="number" min="1" value={attempts} onChange={(e) => setAttempts(e.target.value)} required /></Field><Field label="Peso" name="assessment-weight" required><input id="assessment-weight" className="input" type="number" min="0" step="any" value={weight} onChange={(e) => setWeight(e.target.value)} required /></Field></ActionForm></Dialog></>
}

export function AssessmentPage() {
  const { classId, assessmentId } = useParams(); const { capabilities, notify } = useApp(); const result = useAcademyItem<Assessment>(classId && assessmentId ? ep.classAssessment(classId, assessmentId) : null); const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  const item = result.data
  async function updateAssessment(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!assessmentId) return; setBusy(true); setError(null); try { await academyPatch(ep.assessmentUpdate(assessmentId), { lock_version: item.lock_version, name }); notify('Avaliação actualizada.'); setOpen(false); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title={item.name} back={{ to: `/academia/turmas/${classId}/avaliacoes`, label: 'Voltar às avaliações' }} actions={<div className="row">{capabilities.can('canManage') && <button className="btn btn--secondary" onClick={() => { setName(item.name); setOpen(true) }}>Editar</button>}<Link className="btn btn--primary" to={`/academia/turmas/${classId}/avaliacoes/${assessmentId}/tentativas`}>Ver tentativas</Link></div>} /><section className="card"><dl className="dl"><div className="dl__item"><dt>Nota máxima configurada</dt><dd>{formatNumber(item.max_score)}</dd></div><div className="dl__item"><dt>Nota de referência</dt><dd>{formatNumber(item.pass_score)}</dd></div><div className="dl__item"><dt>Tentativas configuradas</dt><dd>{item.max_attempts}</dd></div><div className="dl__item"><dt>Peso configurado</dt><dd>{formatNumber(item.weight)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={item.status} /></dd></div></dl><p className="field__hint">Estes valores são dados armazenados. A interface não os apresenta como política oficial enquanto D-09 estiver pendente.</p></section><Dialog open={open} title="Editar avaliação" onClose={() => setOpen(false)}><ActionForm busy={busy} submitLabel="Guardar" onSubmit={updateAssessment} error={error}><Field label="Nome" name="assessment-edit-name" required><input id="assessment-edit-name" className="input" value={name} onChange={(e) => setName(e.target.value)} required /></Field></ActionForm></Dialog></>
}

export function AttemptsPage() {
  const { classId, assessmentId } = useParams(); const { capabilities, notify } = useApp(); const { query, update } = useListQuery(false); const result = useAcademyPage<AssessmentAttempt>(classId && assessmentId ? ep.assessmentAttempts(classId, assessmentId) : null, query); const roster = useAcademyPage<RosterRow>(classId ? ep.classRoster(classId) : null, { page: 1, per_page: 100 }); const [open, setOpen] = useState(false); const [enrollment, setEnrollment] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  async function start(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!assessmentId) return; setBusy(true); setError(null); try { await academyPost(ep.attemptStart(assessmentId), { enrollment }); notify('Tentativa iniciada.'); setOpen(false); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title="Tentativas" back={{ to: `/academia/turmas/${classId}/avaliacoes/${assessmentId}`, label: 'Voltar à avaliação' }} actions={capabilities.can('canAssess') ? <button className="btn btn--primary" onClick={() => setOpen(true)}>Iniciar tentativa</button> : undefined} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.id} columns={[{ key: 'name', label: 'Pessoa', render: (r) => r.display_name }, { key: 'number', label: 'Tentativa', render: (r) => r.attempt_number }, { key: 'date', label: 'Início', render: (r) => formatDateTime(r.started_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/tentativas/${r.id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}<Dialog open={open} title="Iniciar tentativa" onClose={() => setOpen(false)}><ActionForm busy={busy} submitLabel="Iniciar" onSubmit={start} error={error}><Field label="Matrícula" name="attempt-enrollment" required><select id="attempt-enrollment" className="select" value={enrollment} onChange={(e) => setEnrollment(e.target.value)} required><option value="">Seleccionar</option>{roster.data?.data.map((row) => <option key={row.enrollment_public_id} value={row.enrollment_public_id}>{row.display_name}</option>)}</select></Field></ActionForm></Dialog></>
}

function GradeDialog({ attemptId, latest, open, onClose, onDone }: { attemptId: string; latest?: GradeVersion; open: boolean; onClose: () => void; onDone: () => void }) {
  const { notify } = useApp(); const [score, setScore] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { if (latest) await academyPost(ep.attemptGradeRevise(attemptId), { score: Number(score), expected_version: latest.version, reason }); else await academyPost(ep.attemptGrades(attemptId), { score: Number(score), reason: reason || null }); notify(latest ? 'Revisão de nota registada.' : 'Nota registada.'); onDone(); onClose() } catch (e) { setError(toUiError(e)) } finally { setBusy(false) } }
  return <Dialog open={open} title={latest ? 'Rever nota' : 'Registar nota'} onClose={onClose}><ActionForm busy={busy} submitLabel={latest ? 'Registar revisão' : 'Registar nota'} onSubmit={submit} error={error}><Field label="Nota" name="score" required><input id="score" className="input" type="number" min="0" step="any" value={score} onChange={(e) => setScore(e.target.value)} required /></Field><Field label="Motivo" name="reason" required={Boolean(latest)}><textarea id="reason" className="textarea" minLength={latest ? 3 : undefined} value={reason} onChange={(e) => setReason(e.target.value)} required={Boolean(latest)} /></Field></ActionForm></Dialog>
}

export function AttemptPage() {
  const { classId, attemptId } = useParams(); const { capabilities, vocabulary, notify } = useApp(); const item = useAcademyItem<AssessmentAttempt>(classId && attemptId ? ep.classAttempt(classId, attemptId) : null); const grades = useAcademyItem<GradeVersion[]>(attemptId ? ep.attemptGrades(attemptId) : null); const [open, setOpen] = useState(false); const [target, setTarget] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  if (item.loading || grades.loading) return <LoadingState />; if (item.error) return <ErrorState error={item.error} retry={item.reload} />; if (!item.data || !attemptId) return null
  const stableAttemptId = attemptId; const history = grades.data ?? []; const latest = history.length > 0 ? history[history.length - 1] : undefined
  const options = targetsFor(vocabulary, 'attempt.transitions', item.data.status)
  async function transition(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!target) return; setBusy(true); setError(null); try { await academyPost(ep.attemptTransition(stableAttemptId), { to_state: target, lock_version: item.data?.lock_version }); notify('Estado da tentativa actualizado.'); item.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  async function finalize() { if (!latest || !window.confirm('Finalizar esta nota?')) return; setBusy(true); setError(null); try { await academyPost(ep.attemptGradeFinalize(stableAttemptId), { lock_version: latest.version }); notify('Nota finalizada.'); grades.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title={item.data.display_name} description={`Tentativa ${item.data.attempt_number} · ${item.data.assessment_name ?? ''}`} back={{ to: `/academia/turmas/${classId}/avaliacoes/${item.data.assessment_public_id}/tentativas`, label: 'Voltar às tentativas' }} actions={capabilities.can('canAssess') ? <div className="row"><button className="btn btn--primary" onClick={() => setOpen(true)}>{latest ? 'Rever nota' : 'Registar nota'}</button>{latest && <button className="btn btn--secondary" disabled={busy} onClick={finalize}>Finalizar nota</button>}</div> : undefined} />{error && <ErrorState error={error} />}{grades.error && <ErrorState error={grades.error} retry={grades.reload} />}<section className="card"><h2>Histórico de notas</h2>{history.length === 0 ? <EmptyState title="Sem nota registada" /> : <ol className="history">{history.map((grade, index) => <li key={grade.version} data-latest={index === history.length - 1}><div className="row"><strong>Versão {grade.version}</strong><StatusBadge value={grade.status} /></div><p>Nota: {formatNumber(grade.score)}</p><p className="muted">{formatDateTime(grade.graded_at)}{grade.reason ? ` · ${grade.reason}` : ''}</p></li>)}</ol>}</section>{capabilities.can('canAssess') && options ? <section className="card"><ActionForm busy={busy} submitLabel="Guardar estado" onSubmit={transition}><Field label="Novo estado" name="attempt-state" required><select id="attempt-state" className="select" value={target} onChange={(e) => setTarget(e.target.value)} required><option value="">Seleccionar</option>{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></Field></ActionForm></section> : <div className="alert alert--warning"><span className="alert__icon">i</span><div className="alert__body"><strong>Transição indisponível</strong><p>{VOCABULARY_PENDING_MESSAGE}</p></div></div>}<GradeDialog attemptId={attemptId} latest={latest} open={open} onClose={() => setOpen(false)} onDone={grades.reload} /></>
}

export function ProgressPage() {
  const { enrollmentId } = useParams(); const { capabilities, notify } = useApp(); const { query, update } = useListQuery(false); const result = useAcademyPage<ProgressPayload>(enrollmentId ? ep.enrollmentProgress(enrollmentId) : null, query); const payload = result.data?.data[0]; const [edit, setEdit] = useState<{ kind: 'lesson' | 'resource'; id: string; label: string } | null>(null); const [value, setValue] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!edit || !enrollmentId) return; setBusy(true); setError(null); try { if (edit.kind === 'lesson') await academyPut(ep.lessonProgress(enrollmentId, edit.id), { ratio: Number(value) }); else await academyPut(ep.resourceProgress(enrollmentId, edit.id), { watched_seconds: Number(value) }); notify('Progresso guardado.'); setEdit(null); result.reload() } catch (problem) { setError(toUiError(problem)) } finally { setBusy(false) } }
  return <><PageHeader title="Progresso" description="Progresso registado na matrícula." back={{ to: '/academia/turmas', label: 'Voltar às turmas' }} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{payload && <div className="stack"><section className="card"><h2>Aulas</h2>{payload.lessons.length === 0 ? <EmptyState /> : <ul className="link-list">{payload.lessons.map((row, i) => <li key={`${row.name}-${i}`}><span>{row.name}</span><span>{formatNumber(row.completion_ratio)} · {row.status}</span>{capabilities.can('canTeach') && row.id && <button className="btn btn--secondary btn--sm" onClick={() => { setValue(String(row.completion_ratio ?? '')); setEdit({ kind: 'lesson', id: String(row.id), label: row.name }) }}>Actualizar</button>}</li>)}</ul>}</section><section className="card"><h2>Recursos</h2>{payload.resources.length === 0 ? <EmptyState /> : <ul className="link-list">{payload.resources.map((row) => <li key={row.public_id}><span>{row.resource_kind}</span><span>{row.watched_seconds ?? 0}s · {row.status}</span>{capabilities.can('canTeach') && <button className="btn btn--secondary btn--sm" onClick={() => { setValue(String(row.watched_seconds ?? 0)); setEdit({ kind: 'resource', id: row.public_id, label: row.resource_kind }) }}>Actualizar</button>}</li>)}</ul>}</section>{result.data && <Pagination meta={result.data.meta} onPage={(page) => update({ page })} />}</div>}<Dialog open={Boolean(edit)} title={`Actualizar ${edit?.label ?? 'progresso'}`} onClose={() => setEdit(null)}><ActionForm busy={busy} submitLabel="Guardar" onSubmit={save} error={error}><Field label={edit?.kind === 'lesson' ? 'Proporção concluída (0 a 1)' : 'Segundos vistos'} name="progress-value" required><input id="progress-value" className="input" type="number" min="0" max={edit?.kind === 'lesson' ? '1' : '86400'} step={edit?.kind === 'lesson' ? '0.01' : '1'} value={value} onChange={(e) => setValue(e.target.value)} required /></Field></ActionForm></Dialog></>
}

export function CertificatesPage() {
  const { classId } = useParams(); const { capabilities, notify } = useApp(); const { query, update } = useListQuery(false); const result = useAcademyPage<Certificate>(classId ? ep.classCertificates(classId) : null, query); const roster = useAcademyPage<RosterRow>(classId ? ep.classRoster(classId) : null, { page: 1, per_page: 100 }); const [open, setOpen] = useState(false); const [enrollment, setEnrollment] = useState(''); const files = useAcademyPage<EligibleFile>(enrollment ? ep.certificateEligibleFiles(enrollment) : null, { page: 1, per_page: 100 }); const [file, setFile] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  async function issue(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { await academyPost(ep.certificateIssue(enrollment), { file }); notify('Certificado emitido.'); setOpen(false); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title="Certificados" back={{ to: `/academia/turmas/${classId}`, label: 'Voltar à turma' }} actions={capabilities.can('canCertify') ? <button className="btn btn--primary" onClick={() => setOpen(true)}>Emitir certificado</button> : undefined} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.public_id} columns={[{ key: 'name', label: 'Pessoa', render: (r) => r.display_name }, { key: 'version', label: 'Versão', render: (r) => r.version }, { key: 'date', label: 'Emissão', render: (r) => formatDateTime(r.issued_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/certificados/${r.public_id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}<Dialog open={open} title="Emitir certificado" onClose={() => setOpen(false)}><ActionForm busy={busy} submitLabel="Emitir" onSubmit={issue} error={error}><Field label="Matrícula" name="certificate-enrollment" required><select id="certificate-enrollment" className="select" value={enrollment} onChange={(e) => { setEnrollment(e.target.value); setFile('') }} required><option value="">Seleccionar</option>{roster.data?.data.map((row) => <option key={row.enrollment_public_id} value={row.enrollment_public_id}>{row.display_name}</option>)}</select></Field><Field label="Ficheiro elegível" name="certificate-file" required><select id="certificate-file" className="select" value={file} onChange={(e) => setFile(e.target.value)} disabled={!enrollment || files.loading} required><option value="">Seleccionar</option>{files.data?.data.map((row) => <option key={row.public_id} value={row.public_id}>{row.file_name} ({row.media_type})</option>)}</select></Field></ActionForm></Dialog></>
}

export function CertificatePage() {
  const { classId, certificateId } = useParams(); const { capabilities, notify } = useApp(); const result = useAcademyItem<Certificate>(classId && certificateId ? ep.classCertificate(classId, certificateId) : null); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  async function revoke() { if (!certificateId || !window.confirm('Revogar este certificado? Esta acção não elimina o registo.')) return; setBusy(true); setError(null); try { await academyPost(ep.certificateRevoke(certificateId), { lock_version: result.data?.lock_version, reason: 'Revogação confirmada na interface' }); notify('Certificado revogado.'); result.reload() } catch (value) { setError(toUiError(value)) } finally { setBusy(false) } }
  return <><PageHeader title="Certificado" description={result.data.display_name} back={{ to: `/academia/turmas/${classId}/certificados`, label: 'Voltar aos certificados' }} actions={capabilities.can('canCertify') && !result.data.revoked_at ? <button className="btn btn--danger" disabled={busy} onClick={revoke}>Revogar</button> : undefined} />{error && <ErrorState error={error} />}<section className="card"><dl className="dl"><div className="dl__item"><dt>Versão</dt><dd>{result.data.version}</dd></div><div className="dl__item"><dt>Emitido em</dt><dd>{formatDateTime(result.data.issued_at)}</dd></div><div className="dl__item"><dt>Revogado em</dt><dd>{formatDateTime(result.data.revoked_at)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={result.data.status} /></dd></div></dl></section><div className="alert alert--info"><span className="alert__icon">i</span><div className="alert__body"><strong>Documento protegido</strong><p>O detalhe não expõe caminho, classificação ou metadata sensível do ficheiro.</p></div></div></>
}

export function TranscriptLandingPage() {
  const { capabilities, notify } = useApp(); const [curriculum, setCurriculum] = useState(''); const [person, setPerson] = useState(''); const [, setParams] = useSearchParams(); const [preview, setPreview] = useState<Transcript | null>(null); const [issueOpen, setIssueOpen] = useState(false); const [file, setFile] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  function submit(e: FormEvent) { e.preventDefault(); setParams({ curriculum, person }) }
  const [params] = useSearchParams(); const selectedCurriculum = params.get('curriculum'); const selectedPerson = params.get('person'); const { query, update } = useListQuery(false); const result = useAcademyPage<TranscriptSummary>(selectedCurriculum && selectedPerson ? ep.transcripts(selectedCurriculum, selectedPerson) : null, query)
  const files = useAcademyPage<EligibleFile>(selectedCurriculum && selectedPerson ? ep.transcriptEligibleFiles(selectedCurriculum, selectedPerson) : null, { page: 1, per_page: 100 })
  async function loadPreview() { if (!selectedCurriculum || !selectedPerson) return; setBusy(true); setError(null); try { const value = await academyPost<Item<Transcript>>(ep.transcriptPreview(selectedCurriculum, selectedPerson)); setPreview(value.data) } catch (problem) { setError(toUiError(problem)) } finally { setBusy(false) } }
  async function issue(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedCurriculum || !selectedPerson) return; setBusy(true); setError(null); try { await academyPost(ep.transcriptIssue(selectedCurriculum, selectedPerson), { file }); notify('Histórico académico emitido.'); setIssueOpen(false); result.reload() } catch (problem) { setError(toUiError(problem)) } finally { setBusy(false) } }
  return <><PageHeader title="Históricos académicos" description="Consulta integral por currículo e pessoa. Uma falha de âmbito não apresenta resultados parciais." actions={selectedCurriculum && selectedPerson ? <div className="row"><button className="btn btn--secondary" disabled={busy} onClick={loadPreview}>Pré-visualizar</button>{capabilities.can('canCertify') && <button className="btn btn--primary" onClick={() => setIssueOpen(true)}>Emitir histórico</button>}</div> : undefined} /><form className="card form form-grid" onSubmit={submit}><Field label="Currículo" name="curriculum" required hint="Identificador numérico fornecido pelo catálogo."><input id="curriculum" className="input" type="number" min="1" value={curriculum} onChange={(e) => setCurriculum(e.target.value)} required /></Field><Field label="Pessoa" name="person" required hint="Identificador público da pessoa."><input id="person" className="input" value={person} onChange={(e) => setPerson(e.target.value.toUpperCase())} required /></Field><button className="btn btn--primary" type="submit">Consultar</button></form>{error && <ErrorState error={error} />}{preview && <section className="card"><h2>Pré-visualização</h2><p>{preview.lines.length} registos. Nenhum documento foi emitido.</p><DataTable rows={preview.lines} rowKey={(row) => row.enrollment_public_id} columns={[{ key: 'class', label: 'Turma', render: (row) => row.class_code }, { key: 'status', label: 'Estado', render: (row) => <StatusBadge value={row.result_status} /> }]} /></section>}{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.public_id} columns={[{ key: 'version', label: 'Versão', render: (r) => r.version }, { key: 'date', label: 'Emissão', render: (r) => formatDateTime(r.issued_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/curriculos/${selectedCurriculum}/pessoas/${selectedPerson}/historicos/${r.public_id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}<Dialog open={issueOpen} title="Emitir histórico académico" onClose={() => setIssueOpen(false)}><ActionForm busy={busy} submitLabel="Emitir" onSubmit={issue} error={error}><Field label="Ficheiro elegível" name="transcript-file" required><select id="transcript-file" className="select" value={file} onChange={(e) => setFile(e.target.value)} disabled={files.loading} required><option value="">Seleccionar</option>{files.data?.data.map((row) => <option key={row.public_id} value={row.public_id}>{row.file_name} ({row.media_type})</option>)}</select></Field></ActionForm></Dialog></>
}

export function TranscriptPage() {
  const { curriculumId, personId, transcriptId } = useParams(); const result = useAcademyItem<Transcript>(curriculumId && personId && transcriptId ? ep.transcript(curriculumId, personId, transcriptId) : null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  return <><PageHeader title="Histórico académico" description={result.data.person.display_name} back={{ to: `/academia/historicos?curriculum=${curriculumId}&person=${personId}`, label: 'Voltar aos históricos' }} /><section className="card"><dl className="dl"><div className="dl__item"><dt>Versão</dt><dd>{result.data.version}</dd></div><div className="dl__item"><dt>Emissão</dt><dd>{formatDateTime(result.data.issued_at)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={result.data.status} /></dd></div></dl></section><section className="card"><h2>Registos</h2><DataTable rows={result.data.lines} rowKey={(r) => r.enrollment_public_id} columns={[{ key: 'class', label: 'Turma', render: (r) => r.class_code }, { key: 'score', label: 'Resultado', render: (r) => formatNumber(r.final_score) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.result_status} /> }]} /></section></>
}
