import { useState, type FormEvent } from 'react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { ActionForm, DataTable, Dialog, EmptyState, ErrorState, Field, LoadingState, PageHeader, Pagination, StatusBadge, type Column } from '../components/ui'
import { useApp } from '../context/AppContext'
import { useAcademyItem, useAcademyPage, useListQuery } from '../hooks/useAcademy'
import { academyPost } from '../lib/academy/client'
import { ep } from '../lib/academy/endpoints'
import { toUiError, type UiError } from '../lib/academy/errors'
import { VOCABULARY_PENDING_MESSAGE } from '../lib/academy/vocabulary'
import { formatDateTime, formatNumber } from '../lib/format'
import type { Assessment, AssessmentAttempt, Certificate, GradeVersion, ProgressPayload, Transcript, TranscriptSummary } from '../types/academy'

export function AttendancePage() {
  const { sessionId } = useParams(); const { query, update } = useListQuery(false)
  const result = useAcademyPage<Record<string, unknown>>(sessionId ? ep.sessionAttendance(sessionId) : null, query)
  return <><PageHeader title="Presenças" description="Registos da sessão, paginados no servidor." back={{ to: '/academia/turmas', label: 'Voltar às turmas' }} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState title="Sem presenças registadas" />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => String(r.enrollment_public_id ?? r.id)} columns={[{ key: 'name', label: 'Pessoa', render: (r) => String(r.display_name ?? '—') }, { key: 'status', label: 'Presença', render: (r) => <StatusBadge value={String(r.status ?? r.attendance_status ?? '')} /> }, { key: 'date', label: 'Registo', render: (r) => formatDateTime(r.recorded_at as string) }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}<div className="alert alert--warning"><span className="alert__icon">i</span><div className="alert__body"><strong>Registo de presença indisponível</strong><p>{VOCABULARY_PENDING_MESSAGE}</p><p>A interface não envia um estado livre nem inventa opções de presença.</p></div></div></>
}

export function AssessmentsPage() {
  const { classId } = useParams(); const { query, update, searchInput, changeSearch } = useListQuery(true)
  const result = useAcademyPage<Assessment>(classId ? ep.classAssessments(classId) : null, query)
  const columns: Column<Assessment>[] = [{ key: 'name', label: 'Avaliação', render: (r) => r.name }, { key: 'max', label: 'Máximo', render: (r) => formatNumber(r.max_score) }, { key: 'weight', label: 'Peso', render: (r) => formatNumber(r.weight) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/avaliacoes/${r.public_id}`}>Abrir</Link> }]
  return <><PageHeader title="Avaliações" description="Avaliações associadas à versão do curso." back={{ to: `/academia/turmas/${classId}`, label: 'Voltar à turma' }} /><div className="card"><label className="field"><span className="field__label">Pesquisar</span><input className="input" value={searchInput} onChange={(e) => changeSearch?.(e.target.value)} /></label></div>{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} columns={columns} rowKey={(r) => r.public_id} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}</>
}

export function AssessmentPage() {
  const { classId, assessmentId } = useParams(); const result = useAcademyItem<Assessment>(classId && assessmentId ? ep.classAssessment(classId, assessmentId) : null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  const item = result.data
  return <><PageHeader title={item.name} back={{ to: `/academia/turmas/${classId}/avaliacoes`, label: 'Voltar às avaliações' }} actions={<Link className="btn btn--primary" to={`/academia/turmas/${classId}/avaliacoes/${assessmentId}/tentativas`}>Ver tentativas</Link>} /><section className="card"><dl className="dl"><div className="dl__item"><dt>Nota máxima configurada</dt><dd>{formatNumber(item.max_score)}</dd></div><div className="dl__item"><dt>Nota de referência</dt><dd>{formatNumber(item.pass_score)}</dd></div><div className="dl__item"><dt>Tentativas configuradas</dt><dd>{item.max_attempts}</dd></div><div className="dl__item"><dt>Peso configurado</dt><dd>{formatNumber(item.weight)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={item.status} /></dd></div></dl><p className="field__hint">Estes valores são dados armazenados. A interface não os apresenta como política oficial enquanto D-09 estiver pendente.</p></section></>
}

export function AttemptsPage() {
  const { classId, assessmentId } = useParams(); const { query, update } = useListQuery(false); const result = useAcademyPage<AssessmentAttempt>(classId && assessmentId ? ep.assessmentAttempts(classId, assessmentId) : null, query)
  return <><PageHeader title="Tentativas" back={{ to: `/academia/turmas/${classId}/avaliacoes/${assessmentId}`, label: 'Voltar à avaliação' }} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.id} columns={[{ key: 'name', label: 'Pessoa', render: (r) => r.display_name }, { key: 'number', label: 'Tentativa', render: (r) => r.attempt_number }, { key: 'date', label: 'Início', render: (r) => formatDateTime(r.started_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/tentativas/${r.id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}</>
}

function GradeDialog({ attemptId, latest, open, onClose, onDone }: { attemptId: string; latest?: GradeVersion; open: boolean; onClose: () => void; onDone: () => void }) {
  const { notify } = useApp(); const [score, setScore] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<UiError | null>(null)
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { if (latest) await academyPost(ep.attemptGradeRevise(attemptId), { score: Number(score), expected_version: latest.version, reason }); else await academyPost(ep.attemptGrades(attemptId), { score: Number(score), reason: reason || null }); notify(latest ? 'Revisão de nota registada.' : 'Nota registada.'); onDone(); onClose() } catch (e) { setError(toUiError(e)) } finally { setBusy(false) } }
  return <Dialog open={open} title={latest ? 'Rever nota' : 'Registar nota'} onClose={onClose}><ActionForm busy={busy} submitLabel={latest ? 'Registar revisão' : 'Registar nota'} onSubmit={submit} error={error}><Field label="Nota" name="score" required><input id="score" className="input" type="number" min="0" step="any" value={score} onChange={(e) => setScore(e.target.value)} required /></Field><Field label="Motivo" name="reason" required={Boolean(latest)}><textarea id="reason" className="textarea" minLength={latest ? 3 : undefined} value={reason} onChange={(e) => setReason(e.target.value)} required={Boolean(latest)} /></Field></ActionForm></Dialog>
}

export function AttemptPage() {
  const { classId, attemptId } = useParams(); const item = useAcademyItem<AssessmentAttempt>(classId && attemptId ? ep.classAttempt(classId, attemptId) : null); const grades = useAcademyItem<GradeVersion[]>(attemptId ? ep.attemptGrades(attemptId) : null); const [open, setOpen] = useState(false)
  if (item.loading || grades.loading) return <LoadingState />; if (item.error) return <ErrorState error={item.error} retry={item.reload} />; if (!item.data || !attemptId) return null
  const history = grades.data ?? []; const latest = history.length > 0 ? history[history.length - 1] : undefined
  return <><PageHeader title={item.data.display_name} description={`Tentativa ${item.data.attempt_number} · ${item.data.assessment_name ?? ''}`} back={{ to: `/academia/turmas/${classId}/avaliacoes/${item.data.assessment_public_id}/tentativas`, label: 'Voltar às tentativas' }} actions={<button className="btn btn--primary" onClick={() => setOpen(true)}>{latest ? 'Rever nota' : 'Registar nota'}</button>} />{grades.error && <ErrorState error={grades.error} retry={grades.reload} />}<section className="card"><h2>Histórico de notas</h2>{history.length === 0 ? <EmptyState title="Sem nota registada" /> : <ol className="history">{history.map((grade, index) => <li key={grade.version} data-latest={index === history.length - 1}><div className="row"><strong>Versão {grade.version}</strong><StatusBadge value={grade.status} /></div><p>Nota: {formatNumber(grade.score)}</p><p className="muted">{formatDateTime(grade.graded_at)}{grade.reason ? ` · ${grade.reason}` : ''}</p></li>)}</ol>}</section><div className="alert alert--warning"><span className="alert__icon">i</span><div className="alert__body"><strong>Transição indisponível</strong><p>{VOCABULARY_PENDING_MESSAGE}</p></div></div><GradeDialog attemptId={attemptId} latest={latest} open={open} onClose={() => setOpen(false)} onDone={grades.reload} /></>
}

export function ProgressPage() {
  const { enrollmentId } = useParams(); const { query, update } = useListQuery(false); const result = useAcademyPage<ProgressPayload>(enrollmentId ? ep.enrollmentProgress(enrollmentId) : null, query); const payload = result.data?.data[0]
  return <><PageHeader title="Progresso" description="Progresso registado na matrícula." back={{ to: '/academia/turmas', label: 'Voltar às turmas' }} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{payload && <div className="stack"><section className="card"><h2>Aulas</h2>{payload.lessons.length === 0 ? <EmptyState /> : <ul className="link-list">{payload.lessons.map((row, i) => <li key={`${row.name}-${i}`}><span>{row.name}</span><span>{formatNumber(row.completion_ratio)} · {row.status}</span></li>)}</ul>}</section><section className="card"><h2>Recursos</h2>{payload.resources.length === 0 ? <EmptyState /> : <ul className="link-list">{payload.resources.map((row) => <li key={row.public_id}><span>{row.resource_kind}</span><span>{row.watched_seconds ?? 0}s · {row.status}</span></li>)}</ul>}</section>{result.data && <Pagination meta={result.data.meta} onPage={(page) => update({ page })} />}</div>}</>
}

export function CertificatesPage() {
  const { classId } = useParams(); const { query, update } = useListQuery(false); const result = useAcademyPage<Certificate>(classId ? ep.classCertificates(classId) : null, query)
  return <><PageHeader title="Certificados" back={{ to: `/academia/turmas/${classId}`, label: 'Voltar à turma' }} />{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.public_id} columns={[{ key: 'name', label: 'Pessoa', render: (r) => r.display_name }, { key: 'version', label: 'Versão', render: (r) => r.version }, { key: 'date', label: 'Emissão', render: (r) => formatDateTime(r.issued_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/turmas/${classId}/certificados/${r.public_id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}</>
}

export function CertificatePage() {
  const { classId, certificateId } = useParams(); const result = useAcademyItem<Certificate>(classId && certificateId ? ep.classCertificate(classId, certificateId) : null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  return <><PageHeader title="Certificado" description={result.data.display_name} back={{ to: `/academia/turmas/${classId}/certificados`, label: 'Voltar aos certificados' }} /><section className="card"><dl className="dl"><div className="dl__item"><dt>Versão</dt><dd>{result.data.version}</dd></div><div className="dl__item"><dt>Emitido em</dt><dd>{formatDateTime(result.data.issued_at)}</dd></div><div className="dl__item"><dt>Revogado em</dt><dd>{formatDateTime(result.data.revoked_at)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={result.data.status} /></dd></div></dl></section><div className="alert alert--warning"><span className="alert__icon">i</span><div className="alert__body"><strong>Ficheiro indisponível</strong><p>A API não fornece um endpoint seguro de download ou pré-visualização. Este ecrã não interpreta a classificação do ficheiro.</p></div></div></>
}

export function TranscriptLandingPage() {
  const [curriculum, setCurriculum] = useState(''); const [person, setPerson] = useState(''); const [, setParams] = useSearchParams()
  function submit(e: FormEvent) { e.preventDefault(); setParams({ curriculum, person }) }
  const [params] = useSearchParams(); const selectedCurriculum = params.get('curriculum'); const selectedPerson = params.get('person'); const { query, update } = useListQuery(false); const result = useAcademyPage<TranscriptSummary>(selectedCurriculum && selectedPerson ? ep.transcripts(selectedCurriculum, selectedPerson) : null, query)
  return <><PageHeader title="Históricos académicos" description="Consulta integral por currículo e pessoa. Uma falha de âmbito não apresenta resultados parciais." /><form className="card form form-grid" onSubmit={submit}><Field label="Currículo" name="curriculum" required hint="Identificador numérico fornecido pelo catálogo."><input id="curriculum" className="input" type="number" min="1" value={curriculum} onChange={(e) => setCurriculum(e.target.value)} required /></Field><Field label="Pessoa" name="person" required hint="Identificador público da pessoa."><input id="person" className="input" value={person} onChange={(e) => setPerson(e.target.value.toUpperCase())} required /></Field><button className="btn btn--primary" type="submit">Consultar</button></form>{result.loading && <LoadingState />}{result.error && <ErrorState error={result.error} retry={result.reload} />}{result.data?.data.length === 0 && <EmptyState />}{result.data && result.data.data.length > 0 && <div className="card"><DataTable rows={result.data.data} rowKey={(r) => r.public_id} columns={[{ key: 'version', label: 'Versão', render: (r) => r.version }, { key: 'date', label: 'Emissão', render: (r) => formatDateTime(r.issued_at) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.status} /> }, { key: 'open', label: '', render: (r) => <Link className="btn btn--secondary btn--sm" to={`/academia/curriculos/${selectedCurriculum}/pessoas/${selectedPerson}/historicos/${r.public_id}`}>Abrir</Link> }]} /><Pagination meta={result.data.meta} onPage={(page) => update({ page })} /></div>}</>
}

export function TranscriptPage() {
  const { curriculumId, personId, transcriptId } = useParams(); const result = useAcademyItem<Transcript>(curriculumId && personId && transcriptId ? ep.transcript(curriculumId, personId, transcriptId) : null)
  if (result.loading) return <LoadingState />; if (result.error) return <ErrorState error={result.error} retry={result.reload} />; if (!result.data) return null
  return <><PageHeader title="Histórico académico" description={result.data.person.display_name} back={{ to: `/academia/historicos?curriculum=${curriculumId}&person=${personId}`, label: 'Voltar aos históricos' }} /><section className="card"><dl className="dl"><div className="dl__item"><dt>Versão</dt><dd>{result.data.version}</dd></div><div className="dl__item"><dt>Emissão</dt><dd>{formatDateTime(result.data.issued_at)}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={result.data.status} /></dd></div></dl></section><section className="card"><h2>Registos</h2><DataTable rows={result.data.lines} rowKey={(r) => r.enrollment_public_id} columns={[{ key: 'class', label: 'Turma', render: (r) => r.class_code }, { key: 'score', label: 'Resultado', render: (r) => formatNumber(r.final_score) }, { key: 'status', label: 'Estado', render: (r) => <StatusBadge value={r.result_status} /> }]} /></section></>
}
