import { useState,type FormEvent } from 'react'
import { Link,useNavigate,useParams,useSearchParams } from 'react-router-dom'
import { ActionForm,DataTable,Dialog,EmptyState,ErrorState,Field,LoadingState,PageHeader,Pagination,StatusBadge } from '../components/ui'
import { useApp } from '../context/AppContext'
import { useTerritorialItem,useTerritorialPage } from '../hooks/useTerritorial'
import { territorialPatch,territorialPost } from '../lib/territorial/client'
import { te } from '../lib/territorial/endpoints'
import { toPeopleError } from '../lib/people/errors'
import type { UiError } from '../lib/academy/errors'
import type { Item } from '../types/academy'
import type { TerritorialUnit } from '../types/territorial'

function Breadcrumb({path}:{path:TerritorialUnit[]}){return <nav className="breadcrumb" aria-label="Percurso institucional"><ol>{path.map(u=><li key={u.public_id}><Link to={`/estrutura-territorial/${u.public_id}`}>{u.name}</Link></li>)}</ol></nav>}

function TreeNode({unit,level=0}:{unit:TerritorialUnit;level?:number}){const[open,setOpen]=useState(false);const children=useTerritorialPage<TerritorialUnit>(te.children(unit.public_id),{per_page:50});return <li className="territorial-node"><div className="territorial-node__row" style={{paddingInlineStart:`${Math.min(level,7)*0.8}rem`}}><button className="btn btn--ghost btn--sm" aria-expanded={open} onClick={()=>setOpen(v=>!v)}>{open?'−':'+'}<span className="sr-only"> filhos de {unit.name}</span></button><Link to={`/estrutura-territorial/${unit.public_id}`}>{unit.name}</Link><span className="badge badge--info">{unit.type_label}</span></div>{open&&<>{children.loading&&<LoadingState/>}{children.error&&<ErrorState error={children.error} retry={children.reload}/>}<ul>{children.data?.data.map(child=><TreeNode key={child.public_id} unit={child} level={level+1}/>)}</ul>{children.data?.data.length===0&&<p className="muted territorial-node__empty">Sem unidades subordinadas.</p>}</>}</li>}

export function TerritorialTreePage(){const roots=useTerritorialPage<TerritorialUnit>(te.roots(),{per_page:50});const{territorial}=useApp();return <><PageHeader title="Estrutura Territorial" description="Expanda apenas os ramos necessários da hierarquia institucional." actions={territorial.has('TERRITORIAL_MANAGE')?<Link className="btn btn--primary" to="/estrutura-territorial/nova">Adicionar unidade</Link>:undefined}/>{roots.loading&&<LoadingState/>}{roots.error&&<ErrorState error={roots.error} retry={roots.reload}/>} {roots.data&&roots.data.data.length===0&&<EmptyState title="Sem raízes visíveis" message="Não existem unidades no seu escopo institucional."/>}{roots.data&&<div className="card"><ul className="territorial-tree">{roots.data.data.map(root=><TreeNode key={root.public_id} unit={root}/>)}</ul></div>}</>}

export function TerritorialListPage(){const[page,setPage]=useState(1);const result=useTerritorialPage<TerritorialUnit>(te.units(),{page,per_page:25});return <><PageHeader title="Lista territorial" description="Consulta paginada das unidades dentro do seu escopo." actions={<Link className="btn btn--secondary" to="/estrutura-territorial">Ver árvore</Link>}/>{result.loading&&<LoadingState/>}{result.error&&<ErrorState error={result.error} retry={result.reload}/>} {result.data&&<div className="card"><DataTable rows={result.data.data} rowKey={u=>u.public_id} columns={[{key:'name',label:'Unidade',render:u=><Link to={`/estrutura-territorial/${u.public_id}`}>{u.name}</Link>},{key:'type',label:'Tipo',render:u=>u.type_label},{key:'status',label:'Estado',render:u=><StatusBadge value={u.status}/>}]}/><Pagination meta={result.data.meta} onPage={setPage}/></div>}</>}

export function TerritorialDetailPage(){const{id}=useParams();const result=useTerritorialItem<TerritorialUnit>(id?te.unit(id):null);const{territorial,notify}=useApp();const[move,setMove]=useState(false);const[busy,setBusy]=useState(false);const[error,setError]=useState<UiError|null>(null);async function submitMove(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!result.data)return;const f=new FormData(e.currentTarget);setBusy(true);setError(null);try{await territorialPost(te.move(result.data.public_id),{new_parent_public_id:f.get('parent'),reason:f.get('reason'),lock_version:result.data.lock_version});notify('Unidade movida com sucesso.');setMove(false);result.reload()}catch(e){setError(toPeopleError(e))}finally{setBusy(false)}}if(result.loading)return <LoadingState/>;if(result.error)return <ErrorState error={result.error} retry={result.reload}/>;if(!result.data)return <EmptyState/>;const u=result.data;return <><Breadcrumb path={u.path??[u]}/><PageHeader title={u.name} description={u.type_label} back={{to:'/estrutura-territorial',label:'Estrutura Territorial'}} actions={<>{territorial.has('TERRITORIAL_MANAGE')&&<><Link className="btn btn--secondary" to={`/estrutura-territorial/${u.public_id}/editar`}>Editar</Link><Link className="btn btn--primary" to={`/estrutura-territorial/nova?parent=${u.public_id}`}>Adicionar subordinada</Link></>}{territorial.has('TERRITORIAL_MOVE')&&u.parent_public_id&&<button className="btn btn--secondary" onClick={()=>setMove(true)}>Mover</button>}</>}/><section className="card"><dl className="dl"><div className="dl__item"><dt>Código</dt><dd>{u.code}</dd></div><div className="dl__item"><dt>Estado</dt><dd><StatusBadge value={u.status}/></dd></div><div className="dl__item"><dt>Aberta em</dt><dd>{u.opened_on??'Não indicada'}</dd></div></dl></section><section><h2>Unidades subordinadas</h2><ChildrenList unit={u.public_id}/></section><Dialog open={move} title="Mover unidade" onClose={()=>setMove(false)}><ActionForm submitLabel="Confirmar reorganização" busy={busy} onSubmit={submitMove} error={error}><Field label="Identificador público do novo superior" name="move-parent" required><input className="input" id="move-parent" name="parent" required minLength={26} maxLength={26}/></Field><Field label="Motivo" name="move-reason" required><textarea className="textarea" id="move-reason" name="reason" required minLength={3}/></Field></ActionForm></Dialog></>}

function ChildrenList({unit}:{unit:string}){const result=useTerritorialPage<TerritorialUnit>(te.children(unit),{per_page:25});if(result.loading)return <LoadingState/>;if(result.error)return <ErrorState error={result.error} retry={result.reload}/>;if(!result.data?.data.length)return <EmptyState/>;return <div className="card"><DataTable rows={result.data.data} rowKey={u=>u.public_id} columns={[{key:'name',label:'Unidade',render:u=><Link to={`/estrutura-territorial/${u.public_id}`}>{u.name}</Link>},{key:'type',label:'Tipo',render:u=>u.type_label},{key:'status',label:'Estado',render:u=><StatusBadge value={u.status}/>} ]}/></div>}

export function TerritorialFormPage(){const{id}=useParams();const[params]=useSearchParams();const editing=Boolean(id);const existing=useTerritorialItem<TerritorialUnit>(id?te.unit(id):null);const{territorial,notify}=useApp();const navigate=useNavigate();const[busy,setBusy]=useState(false);const[error,setError]=useState<UiError|null>(null);if(editing&&existing.loading)return <LoadingState/>;if(existing.error)return <ErrorState error={existing.error} retry={existing.reload}/>;async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setError(null);try{let response:Item<TerritorialUnit>;if(editing&&existing.data)response=await territorialPatch(te.unit(existing.data.public_id),{code:f.get('code'),name:f.get('name'),opened_on:f.get('opened_on')||null,reason:f.get('reason')||null,lock_version:existing.data.lock_version});else response=await territorialPost(te.units(),{parent_public_id:f.get('parent_public_id'),type_code:f.get('type_code'),code:f.get('code'),name:f.get('name'),opened_on:f.get('opened_on')||null,reason:f.get('reason')||null});notify(editing?'Unidade actualizada.':'Unidade criada.');navigate(`/estrutura-territorial/${response.data.public_id}`)}catch(e){setError(toPeopleError(e))}finally{setBusy(false)}}const u=existing.data;return <><PageHeader title={editing?'Editar unidade':'Adicionar unidade'} back={{to:id?`/estrutura-territorial/${id}`:'/estrutura-territorial',label:'Estrutura Territorial'}}/><div className="card"><ActionForm submitLabel={editing?'Guardar alterações':'Criar unidade'} busy={busy} onSubmit={submit} error={error}>{!editing&&<div className="form-grid"><Field label="Unidade superior" name="parent_public_id" required><input className="input" id="parent_public_id" name="parent_public_id" defaultValue={params.get('parent')??''} required minLength={26} maxLength={26}/></Field><Field label="Tipo" name="type_code" required><select className="select" id="type_code" name="type_code" required><option value="">Seleccione</option>{territorial.types.filter(t=>t.code!=='GENERAL_DIRECTION').map(t=><option key={t.code} value={t.code}>{t.label}</option>)}</select></Field></div>}<div className="form-grid"><Field label="Código" name="code" required><input className="input" id="code" name="code" defaultValue={u?.code??''} required maxLength={64}/></Field><Field label="Nome" name="name" required><input className="input" id="name" name="name" defaultValue={u?.name??''} required maxLength={191}/></Field><Field label="Data de abertura" name="opened_on"><input className="input" type="date" id="opened_on" name="opened_on" defaultValue={u?.opened_on??''}/></Field></div><Field label="Motivo/observação" name="reason"><textarea className="textarea" id="reason" name="reason"/></Field></ActionForm></div></>}
