<?php

declare(strict_types=1);

namespace Tests\DatabaseV2;

use Illuminate\Support\Facades\DB;
use Tests\DatabaseV2\Support\TerritorialHttpCase;

final class TerritorialVerticalTest extends TerritorialHttpCase
{
    private static array $fx=[];
    public function test_t01_t03_valid_paths_with_and_without_general_center():void{$g=$this->unit('GENERAL_DIRECTION',null,'DRAFT','Direcção Geral');$a=$this->staff($this->allPermissions(),$g['id']);$r=$this->create($a,$g,'REGIONAL_DIRECTION','REG');$p=$this->create($a,$r,'PROVINCIAL_DIRECTION','PROV');$m1=$this->create($a,$p,'MUNICIPAL_DIRECTION','MUN-A');$c1=$this->create($a,$m1,'CENTER','CENT-A');$co1=$this->create($a,$c1,'CONGREGATION','CONG-A');$m2=$this->create($a,$p,'MUNICIPAL_DIRECTION','MUN-B');$gc=$this->create($a,$m2,'GENERAL_CENTER','CG-B');$c2=$this->create($a,$gc,'CENTER','CENT-B');$co2=$this->create($a,$c2,'CONGREGATION','CONG-B');self::$fx=compact('g','a','r','p','m1','c1','co1','m2','gc','c2','co2');$this->assertSame(201,$co2['status']);}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_t04_invalid_parent_is_denied():void{$f=self::$fx;$this->api($f['a'],'POST','territorial/units',['parent_public_id'=>$f['p']['public_id'],'type_code'=>'CONGREGATION','code'=>'BAD-PARENT','name'=>'Inválida'])->assertStatus(409)->assertJsonPath('error.code','INVALID_PARENT_TYPE');}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_t05_and_t07_cycles_are_denied():void{$f=self::$fx;$row=$this->api($f['a'],'GET','territorial/units/'.$f['r']['public_id'])->assertOk()->json('data');$this->api($f['a'],'POST','territorial/units/'.$f['r']['public_id'].'/move',['new_parent_public_id'=>$f['co1']['public_id'],'reason'=>'cycle probe','lock_version'=>$row['lock_version']])->assertStatus(409)->assertJsonPath('error.code','CYCLE_DETECTED');}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_t06_t09_t10_valid_move_lazy_children_and_path():void{$f=self::$fx;$c3=$this->create($f['a'],$f['m1'],'CENTER','CENT-A2');$row=$this->api($f['a'],'GET','territorial/units/'.$f['co1']['public_id'])->json('data');$moved=$this->api($f['a'],'POST','territorial/units/'.$f['co1']['public_id'].'/move',['new_parent_public_id'=>$c3['public_id'],'reason'=>'reorganização aprovada','lock_version'=>$row['lock_version']])->assertOk()->json('data');$this->assertSame($c3['public_id'],$moved['parent_public_id']);$children=$this->api($f['a'],'GET','territorial/units/'.$c3['public_id'].'/children?per_page=25')->assertOk();$this->assertSame(1,$children->json('meta.total'));$path=$this->api($f['a'],'GET','territorial/units/'.$f['co1']['public_id'].'/path')->assertOk()->json('data');$this->assertSame($c3['public_id'],$path[count($path)-2]['public_id']);}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_t08_wrong_scope_sibling_is_concealed():void{$f=self::$fx;$limited=$this->staff(['TERRITORIAL_VIEW'],$f['m1']['id'],true);$this->api($limited,'GET','territorial/units/'.$f['m2']['public_id'])->assertStatus(404)->assertExactJson(['error'=>['code'=>'RESOURCE_NOT_FOUND','message'=>'The requested resource was not found.']]);}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_scope_matrix_conceals_ancestors_siblings_and_move_targets():void{$f=self::$fx;$limited=$this->staff($this->allPermissions(),$f['m1']['id'],true);$this->api($limited,'GET','territorial/units/'.$f['m1']['public_id'])->assertOk();$this->api($limited,'GET','territorial/units/'.$f['c1']['public_id'])->assertOk();$this->api($limited,'GET','territorial/units/'.$f['p']['public_id'])->assertStatus(404);$this->api($limited,'GET','territorial/units/'.$f['m2']['public_id'].'/children')->assertStatus(404);$row=$this->api($limited,'GET','territorial/units/'.$f['c1']['public_id'])->json('data');$this->api($limited,'POST','territorial/units/'.$f['c1']['public_id'].'/move',['new_parent_public_id'=>$f['m2']['public_id'],'reason'=>'probe de escopo','lock_version'=>$row['lock_version']])->assertStatus(404)->assertJsonPath('error.code','RESOURCE_NOT_FOUND');}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_lifecycle_minimum_center_and_general_center_exclusivity():void{$f=self::$fx;$a=$this->staff($this->allPermissions(),$f['g']['id']);$m=$this->create($a,$f['p'],'MUNICIPAL_DIRECTION','MUN-LIFE');$mrow=$this->api($a,'GET','territorial/units/'.$m['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$m['public_id'].'/lifecycle',['status'=>'ACTIVE','reason'=>'activar município','lock_version'=>$mrow['lock_version']])->assertStatus(409)->assertJsonPath('error.code','MUNICIPAL_CENTER_REQUIRED');$c=$this->create($a,$m,'CENTER','CENT-LIFE');$crow=$this->api($a,'GET','territorial/units/'.$c['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$c['public_id'].'/lifecycle',['status'=>'ACTIVE','reason'=>'activar centro','lock_version'=>$crow['lock_version']])->assertOk();$mrow=$this->api($a,'GET','territorial/units/'.$m['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$m['public_id'].'/lifecycle',['status'=>'ACTIVE','reason'=>'activar município','lock_version'=>$mrow['lock_version']])->assertOk();$crow=$this->api($a,'GET','territorial/units/'.$c['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$c['public_id'].'/lifecycle',['status'=>'CLOSED','reason'=>'não pode remover último centro','lock_version'=>$crow['lock_version']])->assertStatus(409)->assertJsonPath('error.code','MUNICIPAL_CENTER_REQUIRED');$this->api($a,'POST','territorial/units',['parent_public_id'=>$m['public_id'],'type_code'=>'GENERAL_CENTER','code'=>'GC-MIX-'.bin2hex(random_bytes(2)),'name'=>'Centro Geral misto'])->assertStatus(409)->assertJsonPath('error.code','INVALID_PARENT_TYPE');$this->api($a,'POST','territorial/units',['parent_public_id'=>$f['m2']['public_id'],'type_code'=>'GENERAL_CENTER','code'=>'GC-DUP-'.bin2hex(random_bytes(2)),'name'=>'Centro Geral duplicado'])->assertStatus(409)->assertJsonPath('error.code','GENERAL_CENTER_EXISTS');}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_moving_general_center_cannot_empty_active_municipality():void{$f=self::$fx;$a=$this->staff($this->allPermissions(),$f['g']['id']);$mFrom=$this->create($a,$f['p'],'MUNICIPAL_DIRECTION','MUN-GCF');$gc=$this->create($a,$mFrom,'GENERAL_CENTER','GC-F');$center=$this->create($a,$gc,'CENTER','CENT-GCF');$centerRow=$this->api($a,'GET','territorial/units/'.$center['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$center['public_id'].'/lifecycle',['status'=>'ACTIVE','reason'=>'activar centro','lock_version'=>$centerRow['lock_version']])->assertOk();$mRow=$this->api($a,'GET','territorial/units/'.$mFrom['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$mFrom['public_id'].'/lifecycle',['status'=>'ACTIVE','reason'=>'activar município','lock_version'=>$mRow['lock_version']])->assertOk();$mTo=$this->create($a,$f['p'],'MUNICIPAL_DIRECTION','MUN-GCT');$gcRow=$this->api($a,'GET','territorial/units/'.$gc['public_id'])->json('data');$this->api($a,'POST','territorial/units/'.$gc['public_id'].'/move',['new_parent_public_id'=>$mTo['public_id'],'reason'=>'não esvaziar município activo','lock_version'=>$gcRow['lock_version']])->assertStatus(409)->assertJsonPath('error.code','MUNICIPAL_CENTER_REQUIRED');}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_t11_people_context_keeps_same_unit_identity():void{$f=self::$fx;$person=$this->row('people',['full_name'=>'Contexto territorial']);DB::table('person_unit_contexts')->insert(['person_id'=>$person,'unit_id'=>$f['co1']['id'],'context_kind'=>'ONBOARDING','status'=>'ACTIVE','starts_at'=>now('UTC')->subHour()->format('Y-m-d H:i:s.u'),'ends_at'=>null,'reason'=>null,'source_document_id'=>null,'created_at'=>now('UTC')->format('Y-m-d H:i:s.u'),'lock_version'=>0]);$this->assertSame($f['co1']['id'],(int)DB::table('person_unit_contexts')->where('person_id',$person)->value('unit_id'));$this->assertSame($f['co1']['public_id'],(string)DB::table('organizational_units')->where('id',$f['co1']['id'])->value('public_id'));}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_public_payloads_and_audit_are_safe():void{$f=self::$fx;$payload=$this->api($f['a'],'GET','territorial/units/'.$f['co1']['public_id'])->assertOk()->json();array_walk_recursive($payload,function($v,$k){if(is_string($k))$this->assertFalse($k==='id'||($k!=='public_id'&&$k!=='parent_public_id'&&str_ends_with($k,'_id')),'internal id exposed');});$this->assertGreaterThan(0,DB::table('audit_logs')->where('source','P06_TERRITORIAL')->where('action','TERRITORIAL_MOVE')->count());$this->assertGreaterThan(0,DB::table('unit_parent_periods')->where('unit_id',$f['co1']['id'])->count());}
    /** @depends test_t01_t03_valid_paths_with_and_without_general_center */
    public function test_two_simultaneous_moves_serialize_and_recheck_version():void{$f=self::$fx;$root=dirname(__DIR__,4);$a=$this->create($f['a'],$f['m1'],'CENTER','RACE-A');$b=$this->create($f['a'],$f['m1'],'CENTER','RACE-B');$source=$this->create($f['a'],$a,'CONGREGATION','RACE-CONG');$row=DB::table('organizational_units')->where('id',$source['id'])->first();$cmd=['C:\\wamp64\\bin\\php\\php8.1.33\\php.exe',$root.'/scripts/p06-territorial-move-worker.php',$source['public_id'],$a['public_id'],(string)$f['a']['user'],(string)$f['a']['session'],(string)$row->lock_version];$cmd2=$cmd;$cmd2[3]=$b['public_id'];$procs=[];foreach([$cmd,$cmd2]as$c){$p=proc_open($c,[0=>['pipe','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes,$root,getenv());$this->assertIsResource($p);$procs[]=[$p,$pipes];}foreach($procs as[, $pipes]){fwrite($pipes[0],"go\n");fclose($pipes[0]);}$out=[];foreach($procs as[$p,$pipes]){$out[]=json_decode(stream_get_contents($pipes[1]),true,512,JSON_THROW_ON_ERROR);$err=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);$this->assertSame(0,proc_close($p),$err);}sort($out);$statuses=array_column($out,'status');sort($statuses);$this->assertSame(['OK','STALE_WRITE'],$statuses);$final=DB::table('organizational_units')->where('id',$source['id'])->first();$this->assertContains((int)$final->parent_id,[$a['id'],$b['id']]);$this->assertSame(1,DB::table('unit_parent_periods')->where('unit_id',$source['id'])->whereNull('ends_at')->count());}
    private function create(array $actor,array $parent,string $type,string $code):array{$response=$this->api($actor,'POST','territorial/units',['parent_public_id'=>$parent['public_id'],'type_code'=>$type,'code'=>$code.'-'.bin2hex(random_bytes(3)),'name'=>$code])->assertCreated();return ['id'=>(int)DB::table('organizational_units')->where('public_id',$response->json('data.public_id'))->value('id'),'public_id'=>$response->json('data.public_id'),'status'=>$response->status()];}
}
